import type { Config } from "tailwindcss";

// Colours come from the design tokens (src/styles/tokens.css, generated by
// devtools/design_tokens/build.mjs from the Digital Agency Design System). Each is
// "R G B", so opacity modifiers such as bg-primary/10 keep working. Light is the
// default theme; dark is applied by the tokens (data-theme / system preference), so
// the `dark:` variant is not used. Colour names must not reuse a font-size name
// (xs … 9xl, base): `base` once made `text-base` set both size and colour
// (src/__tests__/tailwindNames.test.ts guards this).
const token = (name: string) => `rgb(var(--color-${name}) / <alpha-value>)`;

const config: Config = {
  content: { relative: true, files: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./stories/**/*.{ts,tsx}",
  ] },
  theme: {
    extend: {
      colors: {
        canvas: token("canvas"),
        surface: { DEFAULT: token("surface"), raised: token("surface-raised"), sunken: token("surface-sunken") },
        fg: { DEFAULT: token("fg"), muted: token("fg-muted") },
        line: { DEFAULT: token("line"), strong: token("line-strong") },
        control: token("control"),
        primary: { DEFAULT: token("primary"), hover: token("primary-hover"), fg: token("primary-fg"), soft: token("primary-soft") },
        link: token("link"),
        danger: { DEFAULT: token("danger"), fg: token("danger-fg"), soft: token("danger-soft") },
        success: { DEFAULT: token("success"), soft: token("success-soft") },
        warning: { DEFAULT: token("warning"), soft: token("warning-soft") },
        focus: { DEFAULT: token("focus"), halo: token("focus-halo") },
        muted: token("muted"),
        // Categories: leave kinds (a colour for text and marks, a tint for chips) and weekend days.
        leave: {
          public: token("leave-public"), "public-soft": token("leave-public-soft"), paid: token("leave-paid"), "paid-soft": token("leave-paid-soft"),
          summer: token("leave-summer"), "summer-soft": token("leave-summer-soft"), refresh: token("leave-refresh"), "refresh-soft": token("leave-refresh-soft"),
        },
        saturday: token("saturday"),
        sunday: token("sunday"),
        ring: token("focus"),
      },
      borderColor: { DEFAULT: token("line") },
      ringColor: { DEFAULT: token("focus") },
      ringOffsetColor: { DEFAULT: token("canvas") },
      fontFamily: {
        sans: ["var(--font-family-sans)"],
      },
      borderRadius: { control: "var(--radius-control)", card: "var(--radius-card)" },
      boxShadow: { raised: "var(--elevation-raised)", overlay: "var(--elevation-overlay)" },
    },
  },
  plugins: [],
};
export default config;
