"use client";
import useUnsavedNavigation from '@/features/workspace/shared/useUnsavedNavigation';
import {useEffect,useRef,useState} from 'react';
import ConflictTable from './ConflictTable';
import {API_BASE_URL as API} from '@/lib/apiTarget';
import {errorText} from '@/lib/errorText';
type Evidence={reference:string;status:string;verified_by?:string|null};
const conflictLabels:Record<string,string>={category:'保存区分',purpose:'利用目的',anchor:'起算点',retention_days:'保存日数',legal_minimum_days:'法定の最低保存日数',effective_from:'適用開始',effective_until:'適用終了',owner:'管理責任者',next_review:'次回見直し','evidence.reference':'根拠の参照','evidence.status':'根拠の状態','evidence.verified_by':'根拠の確認者',kind:'請求の種類',reason:'理由',person_id:'本人',status:'状態'};
type Policy={category:string;purpose:string;anchor:string;retention_days:number;legal_minimum_days:number;effective_from:string;effective_until:string;owner:string;next_review:string;evidence:Evidence};
type PrivacyCase={case_id:string;revision:number;status:string;payload:{kind:string;reason:string;person_id:string}};
type State={rules:{revision:number;payload:Policy}[];cases:PrivacyCase[]};
const categories:Record<string,string>={planning_history:'勤務表と入力履歴',compliance:'契約・勤務・休暇の管理記録',identity:'本人・アカウント対応',audit:'監査と通知',privacy_cases:'本人対応の記録',exports:'出力物',backups:'バックアップ',control:'消去・保全・復元制御'};
const states:Record<string,string>={REQUESTED:'受付',VERIFIED:'本人確認済み',APPROVED:'実施承認',COMPLETED:'実施完了',REJECTED:'理由を付して不承認',RELEASED:'利用停止を解除'};
const nextStates:Record<string,string[]>={REQUESTED:['VERIFIED','REJECTED'],VERIFIED:['APPROVED','REJECTED'],APPROVED:['COMPLETED','RELEASED'],COMPLETED:['RELEASED']};
export default function GovernanceForms({scope,admin,onChanged}:{scope:string;admin:boolean;onChanged:()=>void}){
 const [state,setState]=useState<State>({rules:[],cases:[]}),[category,setCategory]=useState('planning_history'),[anchor,setAnchor]=useState(''),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false);
 const [editEpoch,setEditEpoch]=useState(0),[loaded,setLoaded]=useState(false);
 const [conflict,setConflict]=useState<{path:string;base:unknown;current:unknown;proposed:unknown;revision:number}|null>(null);
 const reviewed=useRef<{path:string;revision:number}|null>(null);
 const retry=useRef<{fingerprint:string;key:string}|null>(null);
 async function load(){const r=await fetch(`${API}/planning/compliance/privacy?scope_id=${encodeURIComponent(scope)}`,{credentials:'include',cache:'no-store'});if(!r.ok)throw new Error('保存規則・本人対応の現在版を取得できませんでした。');setState(await r.json());setLoaded(true);}
 useUnsavedNavigation(dirty);
 useEffect(()=>{void load().catch(e=>setError(errorText(e)));},[scope]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{const refresh=()=>void load().catch(e=>setError(errorText(e)));window.addEventListener('planning-records-changed',refresh);return()=>window.removeEventListener('planning-records-changed',refresh);},[scope]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 async function save(path:string,payload:unknown,revision:number){if(conflict)return;if(reviewed.current?.path===path){revision=reviewed.current.revision;if(path.startsWith('/privacy/cases/'))payload={...payload as object,expected_revision:revision};}setBusy(true);setError('');const fingerprint=JSON.stringify({path,payload,revision});if(retry.current?.fingerprint!==fingerprint)retry.current={fingerprint,key:crypto.randomUUID()};try{const r=await fetch(`${API}/planning/compliance${path}?scope_id=${encodeURIComponent(scope)}`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({payload,expected_revision:revision,idempotency_key:retry.current.key})});if(r.status===409){const response=await fetch(`${API}/planning/compliance/privacy?scope_id=${encodeURIComponent(scope)}`,{credentials:'include',cache:'no-store'});if(response.ok){const fresh:State=await response.json();const data=payload as Record<string,unknown>;const old=path==='/retention-rules'?state.rules.filter(x=>x.payload.category===data.category&&x.payload.anchor===data.anchor).sort((a,b)=>b.revision-a.revision)[0]:state.cases.find(x=>path.endsWith('/'+encodeURIComponent(x.case_id)));const current=path==='/retention-rules'?fresh.rules.filter(x=>x.payload.category===data.category&&x.payload.anchor===data.anchor).sort((a,b)=>b.revision-a.revision)[0]:fresh.cases.find(x=>path.endsWith('/'+encodeURIComponent(x.case_id)));if(current)setConflict({path,base:old,current,proposed:payload,revision:current.revision});}}if(!r.ok)throw new Error(r.status===409?'他の更新と競合しました。入力は未保存です。現在版を再読込して差分を確認してください。':'判断を保存できません。入力・根拠・権限を確認してください。');setDirty(false);reviewed.current=null;setConflict(null);setMessage('判断と履歴を記録しました。');await load();onChanged();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 // One category can hold separate rule chains per retention anchor; each chain is revised on its own.
 const chains=state.rules.filter(r=>r.payload.category===category).sort((a,b)=>b.revision-a.revision);
 const chainAnchor=anchor||chains[0]?.payload.anchor||'period_end';
 const latest=chains.find(r=>r.payload.anchor===chainAnchor);const policy=latest?.payload;
 const chainAnchors=chains.map(r=>r.payload.anchor).filter((a,i,all)=>all.indexOf(a)===i);
 const current=state.cases.find(c=>c.case_id===selected);
 if(!loaded)return <div><p role={error?"alert":"status"}>{error||"保存規則・本人対応の現在版を読み込み中…"}</p>{error&&<button className="ui-button ui-button-secondary" onClick={()=>void load().catch(e=>setError(errorText(e)))}>保存規則の読み込みを再試行</button>}</div>;
 return <div className="space-y-3">{admin&&<details><summary>保存規則の確認・改定</summary><p>期間はデータ種別ごとに根拠を照合します。未確認の規則では消去を実行できません。</p>
 <label className="block">対象データ種別<select aria-label="対象データ種別" value={category} disabled={dirty||busy} onChange={e=>{setCategory(e.target.value);setAnchor('');}} className="ui-control block max-w-full">{Object.entries(categories).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="block">保存期間の起算<select aria-label="保存期間の起算" value={chainAnchor} disabled={dirty||busy} onChange={e=>setAnchor(e.target.value)} className="ui-control block"><option value="period_end">対象期間の終了</option><option value="last_activity">最終更新</option><option value="case_closed">本人対応の終了</option><option value="backup_created">バックアップ作成</option></select></label>
 {chainAnchors.length>1&&<p>この種別には起算方法ごとに{chainAnchors.length}件の規則があります。起算方法を選ぶと、その規則だけを改定します。</p>}<p>取得した現在版：{latest?.revision??0}</p>{category==='control'&&<p>制御記録は再作成防止と復元照合に使用します。保存規則を登録しても自動消去せず、必要性と参照関係の個別判断を残します。</p>}
 <form key={category+':'+chainAnchor+':'+(latest?.revision??0)+':'+editEpoch} className="space-y-2" onChange={()=>setDirty(true)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save('/retention-rules',{category,purpose:f.get('purpose'),anchor:chainAnchor,retention_days:Number(f.get('days')),legal_minimum_days:Number(f.get('minimum')),effective_from:f.get('from'),effective_until:f.get('until'),owner:f.get('owner'),next_review:f.get('review'),evidence:{reference:f.get('reference'),status:f.get('verified')?'verified':'unverified',verified_by:f.get('reviewer')||null}},latest?.revision??0);}}>
 <label className="block">利用目的<textarea aria-label="利用目的" name="purpose" required defaultValue={policy?.purpose} className="ui-control block w-full"/></label>
 <label className="block">保存日数<input name="days" required type="number" min="1" defaultValue={policy?.retention_days} className="ui-control block max-w-full"/></label><label className="block">根拠を確認した法定最低保存日数<input name="minimum" required type="number" min="0" defaultValue={policy?.legal_minimum_days} className="ui-control block max-w-full"/></label>
 <label className="block">適用開始日<input name="from" required type="date" defaultValue={policy?.effective_from} className="ui-control block max-w-full"/></label><label className="block">適用終了日（この日を含まない）<input name="until" required type="date" defaultValue={policy?.effective_until} className="ui-control block max-w-full"/></label>
 <label className="block">更新担当者<input name="owner" required defaultValue={policy?.owner} className="ui-control block w-full"/></label><label className="block">次回確認日<input name="review" type="date" required defaultValue={policy?.next_review} className="ui-control block max-w-full"/></label>
 <label className="block">保存根拠・条項<input name="reference" required defaultValue={policy?.evidence.reference} className="ui-control block w-full"/></label><label className="block">保存根拠の確認者<input name="reviewer" className="ui-control block w-full"/></label>
 <label className="flex gap-2"><input name="verified" type="checkbox" className="ui-choice size-6 shrink-0"/>今回の適用範囲・期間・根拠を確認した</label><button className="ui-button ui-button-secondary" disabled={busy||!!conflict}>保存規則の改定を記録</button></form></details>}
 <details><summary>本人対応の進捗{admin?'・判断':''}</summary><ul>{state.cases.map(c=><li key={c.case_id} className="break-words">{c.case_id}：{states[c.status]??c.status}（版 {c.revision}）{admin&&<button className="ui-button ui-button-secondary" disabled={dirty||busy} onClick={()=>setSelected(c.case_id)}>この請求を確認</button>}</li>)}</ul>
 {admin&&current&&<form key={current.case_id+':'+current.revision+':'+editEpoch} className="space-y-2" onChange={()=>setDirty(true)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save(`/privacy/cases/${encodeURIComponent(current.case_id)}`,{expected_revision:current.revision,status:f.get('status'),reason:f.get('reason'),result_reference:f.get('result')||null,identity_evidence:{reference:f.get('reference'),status:'verified',verified_by:f.get('reviewer')}},current.revision);}}>
 <p>対象職員：{current.payload.person_id}／請求：{current.payload.kind}／内容：{current.payload.reason}</p>
 <label className="block">次の判断<select aria-label="次の判断" name="status" required className="ui-control block">{(nextStates[current.status]??[]).map(s=><option key={s} value={s}>{states[s]}</option>)}</select></label><label className="block">判断理由<textarea name="reason" required className="ui-control block w-full"/></label>
 <label className="block">本人確認の根拠<input name="reference" required className="ui-control block w-full"/></label><label className="block">本人確認者<input name="reviewer" required className="ui-control block w-full"/></label><label className="block">実施結果の参照（完了時は必須）<input name="result" className="ui-control block w-full"/></label><button className="ui-button ui-button-secondary" disabled={busy||!!conflict||!(nextStates[current.status]?.length)}>本人対応の判断を記録</button></form>}</details>
 {conflict&&<section aria-label="保存規則・本人対応の競合確認" className="workflow-panel border p-3 break-words"><h3>保存規則・本人対応の競合確認</h3><p role="alert">別の更新があります。三つの内容を比べて確認してください。</p><ConflictTable base={conflict.base} current={conflict.current} proposed={conflict.proposed} labels={conflictLabels}/><button className="ui-button ui-button-secondary" onClick={()=>{reviewed.current={path:conflict.path,revision:conflict.revision};setConflict(null);retry.current=null;setMessage('差分を確認しました。保持した内容を再送してください。');}}>三つの内容を確認して再送を許可</button></section>}
 {dirty&&<p role="status">未保存の変更があります。</p>}<button className="ui-button ui-button-secondary" disabled={busy} onClick={()=>{if(dirty&&!window.confirm('未保存の内容を破棄して現在版を読み込みますか？'))return;setDirty(false);setConflict(null);reviewed.current=null;setEditEpoch(n=>n+1);void load().catch(e=>setError(errorText(e)));}}>現在版を再読込</button>{error&&<p role="alert">{error}</p>}<p role="status">{busy?'処理中…':message}</p></div>;
}
