"use client";
import {useRef,useState} from 'react';
import useUnsavedNavigation,{confirmDiscardChanges} from '@/features/workspace/shared/useUnsavedNavigation';
import {API_BASE_URL as API} from '@/lib/apiTarget';
import {errorText} from '@/lib/errorText';
type Context={owners:string[];participants:{person_id:string;case_id:string;case_revision:number;case_hash:string;control_hash:string;case_reason?:string}[];policy_key:string;policy_revision:number;policy_hash:string;policy_purpose?:string};
type Review={revision:number;source_hash:string;context_hash:string;context:Context;requires_explicit_review:boolean};
export default function JointCopyReview({scope,copyId,label,people,onChanged}:{scope:string;copyId:string;label:string;people:{person_id:string;name:string}[];onChanged:()=>void}){
 const [review,setReview]=useState<Review|null>(null),[reason,setReason]=useState(''),[reference,setReference]=useState(''),[reviewer,setReviewer]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false);
 const retry=useRef<{fingerprint:string;body:string}|null>(null);useUnsavedNavigation(dirty);
 const url=`${API}/planning/compliance/copies/${encodeURIComponent(copyId)}/joint-review?scope_id=${encodeURIComponent(scope)}`;
 async function load(){if(dirty&&!confirmDiscardChanges('共同消去の確認内容を再取得しますか？'))return;setBusy(true);setError('');setReview(null);setConfirmed(false);retry.current=null;try{const r=await fetch(url,{credentials:'include',cache:'no-store'});if(!r.ok)throw new Error('共同消去の条件を取得できません。全所有者の承認・保存期限・保全・対応形式を確認してください。');setReview(await r.json());setDirty(false);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function save(){if(!review||!confirmed)return;setBusy(true);setError('');const payload={expected_revision:review.revision,source_hash:review.source_hash,context_hash:review.context_hash,shared_text_reviewed:true,reason,evidence:{reference,verified_by:reviewer,status:'verified'}};const fingerprint=JSON.stringify(payload);if(retry.current?.fingerprint!==fingerprint)retry.current={fingerprint,body:JSON.stringify({...payload,idempotency_key:crypto.randomUUID()})};try{const r=await fetch(url,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:retry.current.body});if(r.status===409){setReview(null);setConfirmed(false);retry.current=null;throw new Error('所有者・判断・保存規則・原本の版が変わりました。内容を再取得し、明示確認をやり直してください。');}if(!r.ok)throw new Error('判断を保存できません。同じ内容・操作で再送できます。');await r.json();setDirty(false);setReview(null);setConfirmed(false);setMessage('共同消去の判断を記録しました。実消去ではありません。消去計画を再取得してください。');onChanged();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <details className="border rounded-control p-3"><summary>{label}の共同消去判断</summary><p>全所有者の判断を確認します。自動承認や消去実行はしません。共同の自由記述も原本・根拠資料で確認してください。</p><button className="ui-button ui-button-secondary" disabled={busy} onClick={()=>void load()}>全所有者と現在の判断を取得</button>
 {review&&<form className="space-y-2" onSubmit={e=>{e.preventDefault();void save();}} onChange={()=>setDirty(true)}><h5>全所有者と本人対応判断</h5><ul>{review.context.owners.map(id=>{const participant=review.context.participants.find(p=>p.person_id===id);return <li className="break-words" key={id}>{people.find(p=>p.person_id===id)?.name??'氏名未照合'}：{participant?.case_reason??'判断理由は原本で照合してください'}（判断版 {participant?.case_revision??'未確認'}）<details><summary>判断・制御の照合情報</summary><p className="break-all">人物参照 {id}／本人対応参照 {participant?.case_id}／判断hash {participant?.case_hash}／制御hash {participant?.control_hash}</p></details></li>;})}</ul><p className="break-words">現在の保存規則：{review.context.policy_purpose??'利用目的は原本で照合してください'}（版 {review.context.policy_revision}）</p><details><summary>保存規則・原本の照合情報</summary><p className="break-all">規則参照 {review.context.policy_key}／規則hash {review.context.policy_hash}／原本hash {review.source_hash}</p></details>
 <label className="block">共同消去の判断理由<textarea required maxLength={2000} value={reason} disabled={busy} className="ui-control w-full" onChange={e=>setReason(e.target.value)}/></label><label className="block">全所有者と原本を照合した資料<input required value={reference} disabled={busy} className="ui-control w-full" onChange={e=>setReference(e.target.value)}/></label><label className="block">共同消去の確認者<input required value={reviewer} disabled={busy} className="ui-control w-full" onChange={e=>setReviewer(e.target.value)}/></label><label className="block"><input className="ui-choice" type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>全所有者・現在の判断・保存規則・共同自由記述を原本と照合した</label><button className="ui-button ui-button-secondary" disabled={busy||!confirmed||!reason.trim()||!reference.trim()||!reviewer.trim()}>この確認内容の共同判断を保存・同一再送</button></form>}
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</details>;
}
