"use client";
import {useId} from 'react';
export type Schema={type?:string;title?:string;description?:string;$ref?:string;anyOf?:Schema[];properties?:Record<string,Schema>;required?:string[];items?:Schema;enum?:unknown[];default?:unknown;minimum?:number;maximum?:number;format?:string;$defs?:Record<string,Schema>};
const labels:Record<string,string>={establishment_id:'事業場ID',establishments:'事業場',amendment_id:'訂正ID',external_event_id:'外部原本イベントID',external_revision:'外部原本の改定番号',supersedes_revision:'訂正元の改定番号',recorded_at:'記録日時（時差付き）',recording_id:'記録日時の証拠ID',object_kind:'原本の種類',object_id:'原本ID',review_id:'制度確認ID',rule_id:'規則ID',source_url:'一次資料URL',provision:'該当条項',transitional_provision:'経過措置',reviewed_on:'確認日',next_review_on:'次回確認日',copy_id:'コピーID',category:'データ区分',medium:'保存媒体',relative_path:'管理領域内の相対パス',content_hash:'内容ハッシュ',person_ids:'対象職員ID',anchor_at:'保存期間の起算日時',subject_status:'対象者一覧の確認状態',declaration_id:'申告ID',activity:'雇用・非雇用の区分',additional_work:'所定外労働区間',other_holiday_work:'他社の法定休日の労働区間（所定外として通算）',variable_period_days:'変形期間の日数',working_time_system:'労働時間制度の種類',variable_anchor:'変形期間の起算日',review_evidence:'照合の根拠',person_id:'職員ID',name:'氏名',revision_id:'改定ID',relationship_id:'雇用関係ID',employer_id:'雇用主ID',facility_id:'施設ID',department_id:'部署ID',start:'適用開始（時差付き日時）',end:'適用終了（時差付き日時）',reference:'根拠資料の参照',status:'確認状態',verified_by:'確認者',valid_until:'確認の有効期限',evidence:'確認根拠',regime_evidence:'制度の適用根拠',contract_order:'契約締結順',calendar_confirmed:'休日暦の確認済み',statutory_holidays:'法定休日の日付',week_start:'週の起算曜日（0=月曜）',scheduled_work:'所定労働区間',hours_per_day:'1日相当の時間数',hourly_quantum:'時間単位の取得単位',hourly_enabled:'時間単位年休の協定あり',half_day_enabled:'半日年休の合意あり',account_id:'付与ロットID',event_id:'外部イベントID',related_event_id:'元の予約・取得イベントID',quantity:'数量',unit:'取得単位',effective_on:'対象日',reason:'申出・判断理由',kind:'種類',policy_id:'適用規則ID',granted_days:'付与日数',statutory_days:'今回の法定付与日数',granted_on:'付与日',expires_on:'失効日（この日は利用不可）',grant_cycle_id:'付与サイクルID',retention_days:'保存日数',legal_minimum_days:'確認した法定最低日数',purpose:'利用目的',owner:'更新担当者',next_review:'次回確認日',external_id:'外部イベントID',revision:'外部改定番号',duty:'実際の勤務',work:'労働区間',breaks:'休憩区間',source:'入力の出所',task:'業務',location:'勤務場所',engagement:'雇用形態',fixed_term:'有期契約',time_category:'勤務区分',regime:'労働時間制度',external_work_confirmed:'兼業申告の確認済み',period_min_seconds:'対象期間の最低勤務秒数',period_max_seconds:'対象期間の上限勤務秒数',contractual_week_seconds:'週契約秒数',rest_seconds:'勤務間休息秒数',max_consecutive_days:'連続勤務の上限日数',allowed_weekdays:'勤務可能曜日',allowed_kinds:'勤務可能区分'};
export function resolve(schema:Schema,root:Schema):Schema {if(schema.$ref)return root.$defs?.[schema.$ref.split('/').pop()!]??schema;return schema.anyOf?.find(s=>s.type!=='null')?resolve(schema.anyOf.find(s=>s.type!=='null')!,root):schema;}
export function initial(schema:Schema,root:Schema):unknown {const s=resolve(schema,root);if(s.default!==undefined)return s.default;if(s.type==='object')return Object.fromEntries(Object.entries(s.properties??{}).filter(([key])=>s.required?.includes(key)).map(([key,sub])=>[key,initial(sub,root)]));if(s.type==='array')return [];if(s.type==='boolean')return false;return '';}
export default function SchemaFields({schema,root,value,onChange,name='入力',required=false}:{schema:Schema;root:Schema;value:unknown;onChange:(value:unknown)=>void;name?:string;required?:boolean}) {
 const id=useId();const s=resolve(schema,root);const label=labels[name]??name;
 if(!required&&schema.anyOf?.some(option=>option.type==='null')&&s.type==='object'){
  if(value===null||value===undefined)return <div><span>{label}（任意）</span> <button type="button" className="ui-button ui-button-secondary" onClick={()=>onChange(initial(s,root))}>{label}を設定</button></div>;
  return <div><SchemaFields schema={s} root={root} value={value} onChange={onChange} name={name} required/><button type="button" className="ui-button ui-button-secondary" onClick={()=>onChange(undefined)}>{label}を未設定に戻す</button></div>;
 }
 if(s.type==='object'){const object=(value??{}) as Record<string,unknown>;return <fieldset className="workflow-fieldset min-w-0 rounded border p-3 space-y-3"><legend className="px-1 font-medium">{label}</legend>{Object.entries(s.properties??{}).map(([key,sub])=><SchemaFields key={key} schema={sub} root={root} value={object[key]} name={key} required={s.required?.includes(key)} onChange={next=>{const changed={...object};if(next===undefined)delete changed[key];else changed[key]=next;onChange(changed);}}/>)}</fieldset>;}
 if(s.type==='array'){const array=(Array.isArray(value)?value:[]) as unknown[];return <fieldset className="workflow-fieldset min-w-0 border"><legend>{label}</legend>{array.map((item,index)=><div key={index} className="my-2 border-l-2 pl-2"><SchemaFields name={`${label} ${index+1}`} schema={s.items??{}} root={root} value={item} onChange={next=>onChange(array.map((old,i)=>i===index?next:old))}/><button type="button" className="ui-button ui-button-secondary" onClick={()=>onChange(array.filter((_,i)=>i!==index))}>{label} {index+1} を除く</button></div>)}<button type="button" className="ui-button ui-button-secondary" onClick={()=>onChange([...array,initial(s.items??{},root)])}>{label}を追加</button></fieldset>;}
 if(s.type==='boolean')return <label className="flex items-center gap-2"><input className="ui-choice" type="checkbox" checked={value===true} onChange={e=>onChange(e.target.checked)}/>{label}</label>;
 const help=s.description;
 return <div><label htmlFor={id} className="block">{label}{required?'（必須）':''}</label>{s.enum?<select id={id} required={required} className="ui-control max-w-full" value={String(value??'')} onChange={e=>onChange(e.target.value||undefined)}><option value="">未選択</option>{s.enum.map(option=><option key={String(option)} value={String(option)}>{String(option)}</option>)}</select>:<input id={id} required={required} className="ui-control w-full min-w-0" type={s.type==='integer'?'number':s.format==='date'?'date':'text'} min={s.minimum} max={s.maximum} step={s.type==='integer'?1:undefined} placeholder={s.format==='date-time'?'2026-09-22T09:00:00+09:00':undefined} value={String(value??'')} aria-describedby={help?id+'-help':undefined} onChange={e=>onChange(e.target.value===''?undefined:s.type==='integer'?Number(e.target.value):e.target.value)}/ >}{help&&<p id={id+'-help'} className="text-sm">{help}</p>}</div>;
}
