"use client";
import JointCopyReview from './JointCopyReview';
import {useEffect,useRef,useState} from 'react';
import useUnsavedNavigation,{confirmDiscardChanges} from '@/features/workspace/shared/useUnsavedNavigation';
import {API_BASE_URL as API} from '@/lib/apiTarget';
import {errorText} from '@/lib/errorText';
type Case={case_id:string;revision:number;status:string;payload:{person_id:string;kind:string;reason:string}};
type Control={revision:number;state:string;all_copies_erased:boolean;inventory?:unknown};
type Snapshot={control:Control;cases:Case[]};
export default function SubjectControlWorkflow({scope}:{scope:string}){
 const [people,setPeople]=useState<{person_id:string;name:string}[]>([]),[person,setPerson]=useState(''),[snapshot,setSnapshot]=useState<Snapshot|null>(null),[caseId,setCase]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [conflict,setConflict]=useState<{base:Snapshot;current:Snapshot;reason:string}|null>(null);
 const retry=useRef<{fingerprint:string;body:string}|null>(null);useUnsavedNavigation(dirty);
 async function read(path:string){const r=await fetch(`${API}/planning/compliance${path}?scope_id=${encodeURIComponent(scope)}`,{credentials:'include',cache:'no-store'});if(!r.ok)throw new Error('対象・権限・制御サービスを確認できません。');return r.json();}
 async function load(id:string):Promise<Snapshot>{const [control,privacy]=await Promise.all([read('/subject-controls/'+encodeURIComponent(id)),read('/privacy')]);return {control,cases:privacy.cases.filter((c:Case)=>c.payload.person_id===id&&c.payload.kind==='erase')};}
 useEffect(()=>{let active=true;void read('/privacy').then(c=>{if(active)setPeople(c.people);}).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};},[scope]); // eslint-disable-line react-hooks/exhaustive-deps
 async function select(id:string){if(!confirmDiscardChanges('未保存の人物制御判断を破棄しますか？'))return;setBusy(true);setPerson(id);setSnapshot(null);setConflict(null);setCase('');setReason('');setDirty(false);retry.current=null;setError('');setMessage('');try{if(id)setSnapshot(await load(id));}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 const approved=snapshot?.cases.filter(c=>c.status==='APPROVED')??[];const selected=approved.find(c=>c.case_id===caseId);
 async function save(){if(!snapshot||!selected||conflict||snapshot.control.revision!==0)return;setBusy(true);setError('');const payload={expected_revision:snapshot.control.revision,case_id:selected.case_id,case_revision:selected.revision,reason};const fingerprint=JSON.stringify({person,payload});if(retry.current?.fingerprint!==fingerprint)retry.current={fingerprint,body:JSON.stringify({...payload,idempotency_key:crypto.randomUUID()})};try{const r=await fetch(`${API}/planning/compliance/subject-controls/${encodeURIComponent(person)}?scope_id=${encodeURIComponent(scope)}`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:retry.current.body});if(r.status===409){const current=await load(person);setConflict({base:snapshot,current,reason});throw new Error('本人対応・保全・制御の状態が変わりました。三つの内容を確認してください。');}if(!r.ok)throw new Error('制御を適用できません。承認・保存規則・保全・権限を確認してください。');await r.json();setDirty(false);setMessage('人物制御を適用しました。物理消去や全コピー消去の完了ではありません。');setSnapshot(await load(person));}catch(e){setError(errorText(e)+' 通信断では内容を変更せず同じ操作を再送できます。');}finally{setBusy(false);}}
 return <section aria-label="承認済み本人消去の人物制御" className="workflow-panel border p-3 space-y-3"><h3>承認済み本人消去の人物制御</h3><p>安定した職員IDの再作成を制限します。別ID・別名義の人物対応は未確認です。コピーの実消去、保存義務、バックアップ・外部コピーの残存は別途確認してください。</p>
 <label className="block">人物制御の対象職員<select className="ui-control block w-full" disabled={busy} value={person} onChange={e=>void select(e.target.value)}><option value="">選択してください</option>{people.map(p=><option value={p.person_id} key={p.person_id}>{p.name}</option>)}</select></label>{person&&<p data-testid="subject-control-selected-name" className="break-words">選択中の職員：{people.find(p=>p.person_id===person)?.name}</p>}
 {snapshot?.control.revision===1&&<EligibleCopies key={person} scope={scope} person={person} people={people} onChanged={async()=>setSnapshot(await load(person))}/>}
 {snapshot&&<><p role="status">{snapshot.control.revision===0?'人物制御は未適用です。':'人物制御適用済み・コピー残存の確認が必要です。'}</p>{snapshot.control.revision===0&&<form className="space-y-2" onSubmit={e=>{e.preventDefault();void save();}}><label className="block">承認済みの消去判断<select className="ui-control block w-full" required disabled={busy||!!conflict} value={caseId} onChange={e=>{setCase(e.target.value);setDirty(true);}}><option value="">選択してください</option>{approved.map((c,i)=><option key={c.case_id} value={c.case_id}>承認済み判断 {i+1}：{c.payload.reason}</option>)}</select></label>{!approved.length&&<p>承認済みの消去判断がありません。本人対応の判断を先に確認してください。</p>}<label className="block">人物制御の実施理由<textarea className="ui-control block w-full" required maxLength={2000} disabled={busy||!!conflict} value={reason} onChange={e=>{setReason(e.target.value);setDirty(true);}}/></label><button className="ui-button ui-button-secondary" disabled={busy||!!conflict||!selected||!reason.trim()}>人物制御を適用・同一再送</button></form>}<details><summary>残存コピーの照合情報</summary><pre className="whitespace-pre-wrap break-all">{JSON.stringify(snapshot.control.inventory??{state:'未取得'},null,2)}</pre></details></>}
 {conflict&&<section role="alert"><h4>人物制御の競合確認</h4><p>編集開始時：制御版 {conflict.base.control.revision}、判断版 {conflict.base.cases.find(c=>c.case_id===caseId)?.revision??'なし'}、判断状態 {conflict.base.cases.find(c=>c.case_id===caseId)?.status??'なし'}、根拠 {conflict.base.cases.find(c=>c.case_id===caseId)?.payload.reason??'なし'}</p><p>現在：制御版 {conflict.current.control.revision}、判断版 {conflict.current.cases.find(c=>c.case_id===caseId)?.revision??'なし'}、判断状態 {conflict.current.cases.find(c=>c.case_id===caseId)?.status??'なし'}、根拠 {conflict.current.cases.find(c=>c.case_id===caseId)?.payload.reason??'なし'}</p><p>編集中：{conflict.reason}</p><p>保全・承認の理由も本人対応画面で再確認してください。</p><button className="ui-button ui-button-secondary" onClick={()=>{setSnapshot(conflict.current);setConflict(null);retry.current=null;setMessage('現在の判断を確認しました。適用可能な場合だけ再送してください。');}}>差分を確認して現在の判断を採用</button></section>}
 {busy&&<p role="status">処理中…</p>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</section>;
}

type Inventory={targets:{copy_id:string;medium:string;blockers:string[];expires_at:string|null}[];unverified_copies:string[];database_records_remaining:string[]};
type ErasurePlan={plan_id:string;revision:number;fingerprint:string};
function EligibleCopies({scope,person,people,onChanged}:{scope:string;person:string;people:{person_id:string;name:string}[];onChanged:()=>Promise<void>}){
 const [plan,setPlan]=useState<ErasurePlan|null>(null),[inventory,setInventory]=useState<Inventory|null>(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const retry=useRef<{fingerprint:string;body:string}|null>(null);useUnsavedNavigation(confirmed);
 async function request(action:'plans'|'execute'){
  setBusy(true);setError('');const payload=action==='plans'?{expected_revision:1}:{expected_revision:1,plan_id:plan!.plan_id,plan_revision:plan!.revision,fingerprint:plan!.fingerprint};const fingerprint=JSON.stringify({person,action,payload});if(retry.current?.fingerprint!==fingerprint)retry.current={fingerprint,body:JSON.stringify({...payload,idempotency_key:crypto.randomUUID()})};
  try{const r=await fetch(`${API}/planning/compliance/subject-controls/${encodeURIComponent(person)}/${action}?scope_id=${encodeURIComponent(scope)}`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:retry.current.body});if(r.status===409){setPlan(null);setConfirmed(false);retry.current=null;throw new Error('保全・対象・版が変わりました。新しい計画を取得して残存理由を再確認してください。');}if(!r.ok)throw new Error('計画・実行を確認できません。通信断は内容を変えず同じ操作を再送してください。');const result=await r.json();
   if(action==='plans'){const current=await fetch(`${API}/planning/compliance/subject-controls/${encodeURIComponent(person)}?scope_id=${encodeURIComponent(scope)}`,{credentials:'include',cache:'no-store'});if(!current.ok)throw new Error('計画作成後の残存を照合できません。同じ計画取得を再送してください。');const state=await current.json();setInventory(state.inventory);setPlan(result);setConfirmed(false);setMessage('消去計画を取得しました。下の観測内容は実行時にも再照合されます。');}
   else{setPlan(null);setConfirmed(false);retry.current=null;setMessage(`DB消去 ${result.erased_database_count}件、部分履歴 ${result.preserved_archive_count}件、ファイル処理待ち ${result.queued_count}件。全コピー消去完了ではありません。残存を再照合してください。`);await onChanged();}
  }catch(e){setError(errorText(e));}finally{setBusy(false);}
 }
 return <section aria-label="人物制御後の消去可能コピー" className="workflow-panel space-y-2"><h4>人物制御後の消去可能コピー</h4><p>保存規則・保全・共有情報の判断を実行時に再確認します。処理対象が0件でも残存を消去済みにはしません。</p><button className="ui-button ui-button-secondary" disabled={busy} onClick={()=>{if(confirmed&&!confirmDiscardChanges('確認中の消去計画を再取得しますか？'))return;void request('plans');}}>消去計画と残存を取得・再送</button>
 {plan&&inventory&&<><p>対象 {inventory.targets.length}件、現時点で実行可能 {inventory.targets.filter(t=>t.blockers.length===0).length}件、人物参照未確認 {inventory.unverified_copies.length}件、DB参照残存 {inventory.database_records_remaining.length}件。</p><ul>{inventory.targets.map((t,i)=><li className="break-words" key={t.copy_id}>保存物 {i+1}（{t.medium==='database'?'DB記録':t.medium==='backup'?'バックアップ':t.medium==='external'?'外部コピー':'管理ファイル'}）：{t.blockers.length?'残存理由 '+t.blockers.join('、'):'現在の観測では実行可能'}{t.expires_at&&`／期限 ${t.expires_at}`}{t.medium==='file'&&<JointCopyReview scope={scope} copyId={t.copy_id} label={`保存物 ${i+1}`} people={people} onChanged={()=>{setPlan(null);setConfirmed(false);retry.current=null;setMessage('共同判断を記録しました。消去計画を再取得してください。');}}/>}</li>)}</ul><label className="block"><input className="ui-choice" type="checkbox" disabled={busy} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>対象と残存理由を確認し、実行可能分だけの処理に同意した</label><button className="ui-button ui-button-secondary" disabled={busy||!confirmed} onClick={()=>void request('execute')}>この計画の実行可能分を処理・同一再送</button></>}
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</section>;
}
