"""Generate workspace route contracts and page-transition diagrams from usecases.json.

The JSON is the single edited source. Generated files are deterministic and checked in CI.
"""

from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "docs/ideal-ui/usecases.json"
TS_OUT = ROOT / "frontend/src/features/workspace/generated/usecaseRoutes.ts"
MMD_OUT = ROOT / "docs/architecture/er/workspace-transitions.mmd"
TEXT_OUT = ROOT / "docs/architecture/er/workspace-transitions.md"
ROLE_STORIES_OUT = (
    ROOT / "frontend/stories/ideal/CognitiveWorkspace.generated.stories.tsx"
)
STATE_STORIES_OUT = (
    ROOT / "frontend/stories/ideal/CognitiveWorkspace.states.generated.stories.tsx"
)

COMMON_STATES = ("ready", "empty", "loading", "failure", "conflict", "forbidden")


def load_document() -> dict:
    return json.loads(SOURCE.read_text(encoding="utf-8"))


def load() -> list[dict]:
    return load_document()["use_cases"]


def typescript(
    rows: list[dict],
    screens: list[dict] | None = None,
    routes_config: list[dict] | None = None,
) -> str:
    payload = [
        {
            "id": row["id"],
            "screen": row["screen"],
            "view": row["view"],
            "route": row["route"],
            "roles": row["roles"],
            "states": row["states"],
            "transitions": row["transitions"],
            "storybookId": row["storybook_id"],
            "e2eId": row["e2e"],
        }
        for row in rows
    ]
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    routes = sorted(
        {row["route"] for row in rows}
        | {route for row in rows for route in row["transitions"]}
    )
    story_routes = []
    for route in routes:
        parts = route.strip("/").split("/")
        suffix = (
            "today"
            if route == "/workspace/home"
            else "schedule" if route == "/workspace/schedule" else "-".join(parts[1:])
        )
        story_routes.append(
            {
                "route": route,
                "storybookId": f"ideal-ui-v3-cognitive-workspace--{suffix}",
            }
        )
    story_body = json.dumps(story_routes, ensure_ascii=False, indent=2)
    role_stories = [
        {
            "route": route["route"],
            "screen": route["screen"],
            "view": route["view"],
            "role": role,
            "storybookId": "ideal-ui-v3-role-route-matrix--"
            + re.sub(
                r"[^a-z0-9]+", "-", f"{route['screen']}-{route['view']}-{role}".lower()
            ).strip("-"),
        }
        for route in (routes_config or [])
        for role in route["roles"]
    ]
    role_story_body = json.dumps(role_stories, ensure_ascii=False, indent=2)
    state_stories = [
        {
            "route": route["route"],
            "screen": route["screen"],
            "view": route["view"],
            "role": route["roles"][0],
            "state": state,
            "storybookId": "ideal-ui-v3-route-state-matrix--"
            + re.sub(
                r"[^a-z0-9]+",
                "-",
                f"{route['screen']}-{route['view']}-{state}".lower(),
            ).strip("-"),
        }
        for route in (routes_config or [])
        for state in COMMON_STATES
    ]
    state_story_body = json.dumps(state_stories, ensure_ascii=False, indent=2)
    screen_body = json.dumps(screens or [], ensure_ascii=False, indent=2)
    route_config_body = json.dumps(routes_config or [], ensure_ascii=False, indent=2)
    navigation = {
        role: [
            screen["key"]
            for screen in (screens or [])
            if any(
                route["screen"] == screen["key"] and role in route["roles"]
                for route in (routes_config or [])
            )
        ]
        for role in ("ADMIN", "LEADER", "PHARMACIST")
    }
    navigation_body = json.dumps(navigation, ensure_ascii=False, indent=2)
    route_keys = [f"{route['screen']}/{route['view']}" for route in routes_config or []]
    route_key_body = json.dumps(route_keys, ensure_ascii=False, indent=2)
    return (
        "// Generated by devtools/ideal_ui/generate_routes.py. Do not edit.\n"
        f"export const USE_CASE_ROUTES = {body} as const;\n\n"
        f"export const WORKSPACE_SCREENS = {screen_body} as const;\n\n"
        f"export const WORKSPACE_ROUTES = {route_config_body} as const;\n\n"
        f"export const WORKSPACE_NAV = {navigation_body} as const;\n\n"
        f"export const WORKSPACE_ROUTE_KEYS = {route_key_body} as const;\n\n"
        "export type WorkspaceRouteKey = typeof WORKSPACE_ROUTE_KEYS[number];\n"
        'export type WorkspaceRoutePath = typeof WORKSPACE_ROUTES[number]["route"];\n\n'
        f"export const WORKSPACE_STORY_ROUTES = {story_body} as const;\n\n"
        f"export const WORKSPACE_ROLE_STORIES = {role_story_body} as const;\n\n"
        f"export const WORKSPACE_STATE_STORIES = {state_story_body} as const;\n\n"
        'export type WorkspaceUseCaseId = typeof USE_CASE_ROUTES[number]["id"];\n'
        "export const workspaceUseCase = (id: WorkspaceUseCaseId) => "
        "USE_CASE_ROUTES.find((item) => item.id === id)!;\n"
    )


def role_stories(routes: list[dict]) -> str:
    lines = [
        "// Generated by devtools/ideal_ui/generate_routes.py. Do not edit.",
        'import type { Meta, StoryObj } from "@storybook/nextjs-vite";',
        'import CognitiveWorkspaceShowcase from "@/features/workspace/showcase/CognitiveWorkspaceShowcase";',
        'import { workspaceV3Routes } from "./workspaceV3Routes";',
        "",
        'const meta = { title: "Ideal UI v3/Role Route Matrix", component: CognitiveWorkspaceShowcase, parameters: { layout: "fullscreen", fetchRoutes: workspaceV3Routes } } satisfies Meta<typeof CognitiveWorkspaceShowcase>;',
        "export default meta;",
        "type Story = StoryObj<typeof meta>;",
        "",
    ]
    for route in routes:
        for role in route["roles"]:
            export_name = "".join(
                part.title()
                for part in re.split(
                    r"[^A-Za-z0-9]+", f"{route['screen']}-{route['view']}-{role}"
                )
                if part
            )
            view = (
                "undefined" if route["view"] == "index" else json.dumps(route["view"])
            )
            lines.append(
                f"export const {export_name}: Story = {{ args: {{ screen: {json.dumps(route['screen'])}, view: {view}, role: {json.dumps(role)} }} }};"
            )
    return "\n".join(lines) + "\n"


def state_stories(routes: list[dict]) -> str:
    """Generate every route's six common presentation states from one contract."""
    lines = [
        "// Generated by devtools/ideal_ui/generate_routes.py. Do not edit.",
        'import type { Meta, StoryObj } from "@storybook/nextjs-vite";',
        'import CognitiveWorkspaceShowcase from "@/features/workspace/showcase/CognitiveWorkspaceShowcase";',
        'import { workspaceV3Routes } from "./workspaceV3Routes";',
        "",
        'const meta = { title: "Ideal UI v3/Route State Matrix", component: CognitiveWorkspaceShowcase, parameters: { layout: "fullscreen", fetchRoutes: workspaceV3Routes } } satisfies Meta<typeof CognitiveWorkspaceShowcase>;',
        "export default meta;",
        "type Story = StoryObj<typeof meta>;",
        "",
    ]
    for route in routes:
        for state in COMMON_STATES:
            export_name = "".join(
                part.title()
                for part in re.split(
                    r"[^A-Za-z0-9]+",
                    f"{route['screen']}-{route['view']}-{state}",
                )
                if part
            )
            view = (
                "undefined" if route["view"] == "index" else json.dumps(route["view"])
            )
            lines.append(
                f"export const {export_name}: Story = {{ args: {{ screen: {json.dumps(route['screen'])}, view: {view}, role: {json.dumps(route['roles'][0])}, state: {json.dumps(state)} }} }};"
            )
    return "\n".join(lines) + "\n"


def node(route: str) -> str:
    return "route_" + re.sub(r"[^a-z0-9]+", "_", route.lower()).strip("_")


def mermaid(rows: list[dict]) -> str:
    routes = sorted(
        {row["route"] for row in rows}
        | {route for row in rows for route in row["transitions"]}
    )
    edge_ids: dict[tuple[str, str], list[str]] = defaultdict(list)
    for row in rows:
        for target in row["transitions"]:
            if target != row["route"]:
                edge_ids[(row["route"], target)].append(row["id"])
    lines = [
        "%% Generated by devtools/ideal_ui/generate_routes.py. Do not edit.",
        "flowchart LR",
        "  accTitle: 認知中心UI v3のページ間遷移",
        f"  accDescr: {len(rows)}業務系列で許可された8入口・25子画面間の遷移。任意URLは入力として受け取らない。",
    ]
    for route in routes:
        lines.append(f'  {node(route)}["{route}"]')
    for (source, target), ids in sorted(edge_ids.items()):
        lines.append(f'  {node(source)} -->|"{",".join(ids)}"| {node(target)}')
    return "\n".join(lines) + "\n"


def text(rows: list[dict]) -> str:
    lines = [
        "<!-- Generated by devtools/ideal_ui/generate_routes.py. Do not edit. -->",
        "# 認知中心UI v3・ページ間遷移（テキスト代替）",
        "",
        "図を利用できない場合の同内容表。遷移先は列挙済みrouteだけで、任意URLを戻り先として受け取らない。",
        "",
        "| 系列 | 起点 | 許可された関連画面 | 役割 |",
        "|---|---|---|---|",
    ]
    for row in rows:
        targets = "<br>".join(f"`{item}`" for item in row["transitions"])
        lines.append(
            f"| {row['id']} {row['title']} | `{row['route']}` | {targets} | {', '.join(row['roles'])} |"
        )
    return "\n".join(lines) + "\n"


def outputs() -> dict[Path, str]:
    document = load_document()
    rows = document["use_cases"]
    return {
        TS_OUT: typescript(
            rows, document["workspace_screens"], document["workspace_routes"]
        ),
        MMD_OUT: mermaid(rows),
        TEXT_OUT: text(rows),
        ROLE_STORIES_OUT: role_stories(document["workspace_routes"]),
        STATE_STORIES_OUT: state_stories(document["workspace_routes"]),
    }


def main(argv: list[str]) -> int:
    generated = outputs()
    if "--check" in argv:
        stale = [
            str(path.relative_to(ROOT))
            for path, value in generated.items()
            if not path.exists() or path.read_text(encoding="utf-8") != value
        ]
        print(
            "workspace route outputs are current"
            if not stale
            else "stale: " + ", ".join(stale)
        )
        return 1 if stale else 0
    if "--write" in argv:
        for path, value in generated.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(value, encoding="utf-8")
        print("wrote workspace route contract and transition diagrams")
        return 0
    document = load_document()
    sys.stdout.write(
        typescript(
            document["use_cases"],
            document["workspace_screens"],
            document["workspace_routes"],
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
