days:
  - date: 2025-11-01
    day_type: SATURDAY
    is_business_day: true
  - date: 2025-11-02
    day_type: SUNDAY
    is_business_day: true
  - date: 2025-11-03
    day_type: HOLIDAY
    is_business_day: true
  - date: 2025-11-04
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-05
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-06
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-07
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-08
    day_type: SATURDAY
    is_business_day: true
  - date: 2025-11-09
    day_type: SUNDAY
    is_business_day: true
  - date: 2025-11-10
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-11
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-12
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-13
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-14
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-15
    day_type: SATURDAY
    is_business_day: true
  - date: 2025-11-16
    day_type: SUNDAY
    is_business_day: true
  - date: 2025-11-17
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-18
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-19
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-20
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-21
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-22
    day_type: SATURDAY
    is_business_day: true
  - date: 2025-11-23
    day_type: SUNDAY
    is_business_day: true
  - date: 2025-11-24
    day_type: HOLIDAY
    is_business_day: true
  - date: 2025-11-25
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-26
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-27
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-28
    day_type: WEEKDAY
    is_business_day: true
  - date: 2025-11-29
    day_type: SATURDAY
    is_business_day: true
  - date: 2025-11-30
    day_type: SUNDAY
    is_business_day: true
