"use client";
import {useState} from 'react';
import {overlapsDisplay} from '@/lib/calendar';
type Duty={display_key?:string;duty_id:string;person_id:string;start:string;end:string;kind:string;task:string;location:string};
const displayKey=(d:Duty)=>d.display_key??JSON.stringify(['draft',d.duty_id]);
const kindLabel=(kind:string)=>({DAY_SHIFT:'日勤',EVENING_SHIFT:'遅番',NIGHT_SHIFT:'夜勤',DAY:'日勤',NIGHT:'夜勤'}[kind]??kind);
const dayKey=(value:string)=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
const occursOn=(d:Duty, day:string)=>{const start=day+'T00:00:00+09:00';return overlapsDisplay(d,{start,end:new Date(Date.parse(start)+86400000).toISOString()});};
// People on flextime set their own hours: they have no timed duty, which the row
// says in words instead of leaving an unexplained empty row.
export default function MonthlySchedule({people,duties,previous,period,draft,published,flexPeople=[],fixedDuties=[]}:{people:{person_id:string;name:string}[];duties:Duty[];previous:Duty[];period?:{start:string;end:string};draft:boolean;published:boolean;flexPeople?:string[];fixedDuties?:Duty[]}){
 const [selected,setSelected]=useState<Duty|null>(null);
 const [listDay,setListDay]=useState(''),[listPerson,setListPerson]=useState('');
 const displayDuties=[...duties,...fixedDuties].sort((a,b)=>Date.parse(a.start)-Date.parse(b.start)||displayKey(a).localeCompare(displayKey(b)));const fixed=new Set(fixedDuties.map(displayKey));
 const first=period?.start??displayDuties[0]?.start;if(!first)return <p>表示できる勤務はありません。</p>;
 const start=new Date(first);const end=period?new Date(period.end):new Date(start.getTime()+31*86400000);const days:string[]=[];
 for(let date=new Date(start);date<end&&days.length<62;date=new Date(date.getTime()+86400000))days.push(dayKey(date.toISOString()));
 const peopleById=new Map(people.map(p=>[p.person_id,p]));for(const d of [...displayDuties,...previous])if(!peopleById.has(d.person_id))peopleById.set(d.person_id,{person_id:d.person_id,name:d.person_id});const persons=Array.from(peopleById.values());const old=new Set(previous.map(d=>d.duty_id));const activeDay=days.includes(listDay)?listDay:days[0];
 return <section aria-labelledby="month-title" className="space-y-3"><h2 id="month-title" className="text-xl font-semibold">月間勤務表 — {draft?'下書き（未公開）':published?'公開済み':'未生成・未公開'}</h2><p>{dayKey(start.toISOString())}〜{dayKey(new Date(end.getTime()-1).toISOString())}（日本時間）</p><p>勤務を選ぶと詳細を表示します。日を跨ぐ勤務は両日に表示します。</p>{!persons.length&&<p role="status">この期間の勤務割当はありません。</p>}<div className="md:hidden rounded-lg border border-line bg-surface p-3 space-y-3" aria-label="日別・職員別の勤務一覧">
  <div className="flex flex-wrap gap-3"><label className="min-w-0 max-w-full">表示日<select className="ui-control block mt-1 min-h-11 max-w-full rounded-lg border border-control bg-surface px-3 py-2 text-fg" value={activeDay} onChange={e=>setListDay(e.target.value)}>{days.map(day=><option key={day}>{day}</option>)}</select></label><label className="min-w-0 max-w-full">職員<select className="ui-control block mt-1 min-h-11 max-w-full rounded-lg border border-control bg-surface px-3 py-2 text-fg" value={listPerson} onChange={e=>setListPerson(e.target.value)}><option value="">全員</option>{persons.map(p=><option key={p.person_id} value={p.person_id}>{p.name}</option>)}</select></label></div>
  {persons.filter(p=>!listPerson||p.person_id===listPerson).map(p=>{const matches=displayDuties.filter(d=>d.person_id===p.person_id&&occursOn(d,activeDay));const removed=previous.filter(d=>d.person_id===p.person_id&&occursOn(d,activeDay)&&!duties.some(now=>now.duty_id===d.duty_id));return <section key={p.person_id} className="workflow-panel border-t border-line pt-3"><h3 className="font-semibold break-words">{p.name}</h3>{matches.map(d=><button key={displayKey(d)} type="button" className="ui-button ui-button-secondary ui-table-action block w-full border p-3 text-left my-2" onClick={()=>setSelected(d)}>{kindLabel(d.kind)} — {new Date(d.start).toLocaleTimeString('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit'})}〜{new Date(d.end).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}{draft&&!fixed.has(displayKey(d))&&!old.has(d.duty_id)&&'（追加）'}{fixed.has(displayKey(d))&&<span className="block text-sm">別期間の公開勤務（固定）</span>}<span className="block text-sm">詳細を表示</span></button>)}{!matches.length&&<p>{flexPeople.includes(p.person_id)?'フレックスタイム制（時刻付き勤務の割当なし）':'割当なし'}</p>}{draft&&removed.map(d=><p key={displayKey(d)}>削除：{kindLabel(d.kind)}</p>)}</section>;})}
 </div><div className="hidden md:block overflow-auto max-h-[32rem] rounded-lg border border-line" role="region" aria-label="月間勤務表（横スクロール可能）" tabIndex={0}><table className="ui-data-table border-collapse text-sm schedule-dense"><caption className="sr-only">職員別・日別の勤務</caption><thead><tr><th className="sticky left-0 bg-surface p-2">職員</th>{days.map(day=><th key={day} className="p-2 whitespace-nowrap" scope="col">{day.slice(5)}</th>)}</tr></thead><tbody>{persons.map(person=><tr key={person.person_id}><th scope="row" className="sticky left-0 bg-surface p-2 min-w-32 max-w-48 break-words">{person.name}{flexPeople.includes(person.person_id)&&<span className="block text-sm font-normal">フレックスタイム制（時刻付き勤務の割当なし）</span>}</th>{days.map(day=>{const matches=displayDuties.filter(d=>d.person_id===person.person_id&&occursOn(d,day));const removed=previous.filter(d=>d.person_id===person.person_id&&occursOn(d,day)&&!duties.some(now=>now.duty_id===d.duty_id));return <td key={day} className="border p-1 align-top min-w-20">{matches.map(d=><button type="button" key={displayKey(d)} className="ui-button ui-button-secondary ui-table-action block w-full text-left focus-visible:outline focus-visible:outline-2" onClick={()=>setSelected(d)} aria-label={`${person.name} ${day} ${kindLabel(d.kind)} 詳細`}>{kindLabel(d.kind)}{draft&&!fixed.has(displayKey(d))&&!old.has(d.duty_id)&&<span className="block text-xs">追加</span>}{fixed.has(displayKey(d))&&<span className="block text-xs">別期間の公開勤務（固定）</span>}</button>)}{draft&&removed.map(d=><span key={displayKey(d)} className="block text-xs">削除：{kindLabel(d.kind)}</span>)}{!matches.length&&!removed.length&&<span aria-label={flexPeople.includes(person.person_id)?'フレックスタイム制のため割当なし':'割当なし'}>—</span>}</td>;})}</tr>)}</tbody></table></div>{selected&&displayDuties.some(d=>displayKey(d)===displayKey(selected))&&<div className="border p-3" role="status"><p>{persons.find(p=>p.person_id===selected.person_id)?.name}：{kindLabel(selected.kind)}</p><p>{selected.start} 〜 {selected.end}</p><p>{selected.task} / {selected.location}</p><button className="ui-button ui-button-secondary ui-table-action" onClick={()=>setSelected(null)}>詳細を閉じる</button></div>}</section>;
}
