import {render,screen,fireEvent} from '@testing-library/react';
import JointCopyReview from '../JointCopyReview';
const context={owners:['p1','p2'],participants:[{person_id:'p1',case_id:'case1',case_revision:3,case_hash:'a',control_hash:'b',case_reason:'本人一の承認'},{person_id:'p2',case_id:'case2',case_revision:4,case_hash:'c',control_hash:'d',case_reason:'本人二の承認'}],policy_key:'policy',policy_revision:5,policy_hash:'e',policy_purpose:'期限満了の共有記録'};
const source={revision:7,source_hash:'1'.repeat(64),context_hash:'2'.repeat(64),context,requires_explicit_review:true};
let mode:string,bodies:any[];
beforeEach(()=>{window.confirm=jest.fn(()=>true);mode='normal';bodies=[];Object.defineProperty(global.crypto,'randomUUID',{configurable:true,value:()=> 'joint-operation-key'});global.fetch=jest.fn(async(_u:any,o:any)=>{if(o?.method==='POST'){bodies.push(JSON.parse(o.body));if(mode==='lost'&&bodies.length===1)throw new TypeError('ACK lost');if(mode==='conflict')return {ok:false,status:409};}return {ok:true,status:200,json:async()=>source};}) as any;});
async function prepare(){render(<JointCopyReview scope="hospital/pharmacy" copyId="copy1" label="保存物 1" people={[{person_id:'p1',name:'職員一'},{person_id:'p2',name:'職員二'}]} onChanged={()=>{}}/>);fireEvent.click(screen.getByText('保存物 1の共同消去判断'));fireEvent.click(screen.getByRole('button',{name:'全所有者と現在の判断を取得'}));await screen.findByText(/職員一：本人一の承認/);expect(screen.getByText(/職員二：本人二の承認/)).toBeInTheDocument();expect(screen.getByText(/期限満了の共有記録/)).toBeInTheDocument();expect(bodies).toHaveLength(0);for(const [label,value] of [['共同消去の判断理由','照合済みの判断'],['全所有者と原本を照合した資料','原本資料'],['共同消去の確認者','責任者']])fireEvent.change(screen.getByLabelText(label),{target:{value}});expect(screen.getByRole('button',{name:'この確認内容の共同判断を保存・同一再送'})).toBeDisabled();fireEvent.click(screen.getByLabelText('全所有者・現在の判断・保存規則・共同自由記述を原本と照合した'));}
test('explicit owners policy and free text review; same body after response loss',async()=>{mode='lost';await prepare();fireEvent.click(screen.getByRole('button',{name:'この確認内容の共同判断を保存・同一再送'}));await screen.findByRole('alert');fireEvent.click(screen.getByRole('button',{name:'この確認内容の共同判断を保存・同一再送'}));await screen.findByText(/共同消去の判断を記録しました/);expect(bodies).toHaveLength(2);expect(bodies[1]).toEqual(bodies[0]);expect(bodies[0]).toMatchObject({expected_revision:7,source_hash:source.source_hash,context_hash:source.context_hash,shared_text_reviewed:true,evidence:{status:'verified'}});});
test('changed context cannot be implicitly approved after conflict',async()=>{mode='conflict';await prepare();fireEvent.click(screen.getByRole('button',{name:'この確認内容の共同判断を保存・同一再送'}));await screen.findByText(/内容を再取得し、明示確認をやり直してください/);expect(screen.queryByRole('button',{name:'この確認内容の共同判断を保存・同一再送'})).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'全所有者と現在の判断を取得'}));await screen.findByText(/職員一：本人一の承認/);expect(screen.getByRole('button',{name:'この確認内容の共同判断を保存・同一再送'})).toBeDisabled();expect(bodies).toHaveLength(1);});
