import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import SubjectControlWorkflow from '../SubjectControlWorkflow';
const ok=(data:unknown,status=200)=>({ok:status===200,status,json:async()=>data});
let posts:any[],caseRevision:number,applied:boolean,mode:string;
beforeEach(()=>{posts=[];caseRevision=1;applied=false;mode='normal';let key=0;Object.defineProperty(global.crypto,'randomUUID',{configurable:true,value:()=>`operation-${++key}`});global.fetch=jest.fn(async(u:any,o:any)=>{if(o?.method==='POST'){posts.push(JSON.parse(o.body));if(mode==='lost'&&posts.length===1){applied=true;throw new TypeError('network lost');}if(mode==='conflict'&&posts.length===1){caseRevision=2;return ok({},409);}applied=true;return ok({revision:1});}if(String(u).includes('/privacy'))return ok({people:[{person_id:'p1',name:'対象職員'}],cases:[{case_id:'case-1',revision:caseRevision,status:'APPROVED',payload:{person_id:'p1',kind:'erase',reason:'本人確認済みの消去判断'}},{case_id:'case-other',revision:1,status:'APPROVED',payload:{person_id:'p2',kind:'erase',reason:'他人の判断'}}]});return ok({revision:applied?1:0,state:applied?'CONTROL_APPLIED_REMAINS':'NOT_APPLIED',all_copies_erased:false,inventory:{remaining:1}});}) as any;});
async function fill(){render(<SubjectControlWorkflow scope="hospital/pharmacy"/>);await screen.findByRole('option',{name:'対象職員'});fireEvent.change(screen.getByLabelText('人物制御の対象職員'),{target:{value:'p1'}});await screen.findByText('人物制御は未適用です。');expect(screen.queryByText(/他人の判断/)).not.toBeInTheDocument();fireEvent.change(screen.getByLabelText('承認済みの消去判断'),{target:{value:'case-1'}});fireEvent.change(screen.getByLabelText('人物制御の実施理由'),{target:{value:'承認を照合して制御する'}});}
test('approved identity and revisions come from API; control is not physical erasure',async()=>{await fill();fireEvent.click(screen.getByRole('button',{name:'人物制御を適用・同一再送'}));await screen.findByText('人物制御適用済み・コピー残存の確認が必要です。');expect(posts[0]).toMatchObject({expected_revision:0,case_id:'case-1',case_revision:1});expect(screen.getByText(/物理消去や全コピー消去の完了ではありません/)).toBeVisible();});
test('candidate roster uses the exact-scope privacy endpoint',async()=>{render(<SubjectControlWorkflow scope="hospital/pharmacy"/>);await screen.findByRole('option',{name:'対象職員'});expect(global.fetch).not.toHaveBeenCalledWith(expect.stringContaining('/copies/context'),expect.anything());expect(screen.queryByRole('option',{name:'別部署職員'})).not.toBeInTheDocument();});
test('response loss reuses exact request even when server already committed',async()=>{mode='lost';await fill();fireEvent.click(screen.getByRole('button',{name:'人物制御を適用・同一再送'}));await screen.findByRole('alert');fireEvent.click(screen.getByRole('button',{name:'人物制御を適用・同一再送'}));await screen.findByText('人物制御適用済み・コピー残存の確認が必要です。');expect(posts).toHaveLength(2);expect(posts[1]).toEqual(posts[0]);});
test('conflict requires explicit review before adopting current decision',async()=>{mode='conflict';await fill();fireEvent.click(screen.getByRole('button',{name:'人物制御を適用・同一再送'}));await screen.findByText('人物制御の競合確認');expect(screen.getByRole('button',{name:'人物制御を適用・同一再送'})).toBeDisabled();expect(posts).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'差分を確認して現在の判断を採用'}));fireEvent.click(screen.getByRole('button',{name:'人物制御を適用・同一再送'}));await waitFor(()=>expect(posts).toHaveLength(2));expect(posts[1].case_revision).toBe(2);expect(posts[1].idempotency_key).not.toBe(posts[0].idempotency_key);});
test('eligible plan needs confirmation and retries exact execute body without claiming all copies erased',async()=>{
 await fill();fireEvent.click(screen.getByRole('button',{name:'人物制御を適用・同一再送'}));await screen.findByText('人物制御適用済み・コピー残存の確認が必要です。');
 const original=global.fetch;let tries=0;const bodies:any[]=[];
 global.fetch=jest.fn(async(u:any,o:any)=>{if(String(u).includes('/plans'))return ok({plan_id:'plan',revision:1,fingerprint:'a'.repeat(64)});if(String(u).includes('/execute')){bodies.push(JSON.parse(o.body));if(++tries===1)throw new TypeError('lost ACK');return ok({erased_database_count:0,preserved_archive_count:0,queued_count:0,all_copies_erased:false});}if(String(u).includes('/subject-controls/'))return ok({revision:1,state:'CONTROL_APPLIED_REMAINS',inventory:{targets:[{copy_id:'remaining',medium:'backup',blockers:['legal_hold'],expires_at:null}],unverified_copies:[],database_records_remaining:['retained']}});return original(u,o);}) as any;
 fireEvent.click(screen.getByRole('button',{name:'消去計画と残存を取得・再送'}));const execute=await screen.findByRole('button',{name:'この計画の実行可能分を処理・同一再送'});expect(execute).toBeDisabled();fireEvent.click(screen.getByLabelText('対象と残存理由を確認し、実行可能分だけの処理に同意した'));fireEvent.click(execute);await screen.findByRole('alert');fireEvent.click(execute);await screen.findByText(/DB消去 0件/);expect(bodies[1]).toEqual(bodies[0]);expect(screen.getByText(/DB消去 0件/)).toHaveTextContent('全コピー消去完了ではありません');
});
test('eligible execution conflict invalidates plan and requires a fresh confirmation',async()=>{
 await fill();fireEvent.click(screen.getByRole('button',{name:'人物制御を適用・同一再送'}));await screen.findByText('人物制御適用済み・コピー残存の確認が必要です。');const original=global.fetch;
 global.fetch=jest.fn(async(u:any,o:any)=>{if(String(u).includes('/plans'))return ok({plan_id:'plan',revision:1,fingerprint:'b'.repeat(64)});if(String(u).includes('/execute'))return ok({},409);if(String(u).includes('/subject-controls/'))return ok({revision:1,state:'CONTROL_APPLIED_REMAINS',inventory:{targets:[],unverified_copies:[],database_records_remaining:[]}});return original(u,o);}) as any;
 fireEvent.click(screen.getByRole('button',{name:'消去計画と残存を取得・再送'}));await screen.findByLabelText('対象と残存理由を確認し、実行可能分だけの処理に同意した');fireEvent.click(screen.getByLabelText('対象と残存理由を確認し、実行可能分だけの処理に同意した'));fireEvent.click(screen.getByRole('button',{name:'この計画の実行可能分を処理・同一再送'}));await screen.findByText(/新しい計画を取得して残存理由を再確認/);expect(screen.queryByRole('button',{name:'この計画の実行可能分を処理・同一再送'})).not.toBeInTheDocument();
});
