"""Lock already tested distributions with PyPI release SHA-256 metadata.

This does not select newer versions. pip --require-hashes verifies downloaded bytes.
Targets Python 3.12 on Linux x86_64/aarch64 and macOS arm64.
"""

from __future__ import annotations

import importlib.metadata as metadata
import json
import ssl
import tomllib
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import certifi
from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


def main():
    project = tomllib.loads(Path("pyproject.toml").read_text())["project"]
    environments = []
    for system, platform, machine in (
        ("Linux", "linux", "x86_64"),
        ("Linux", "linux", "aarch64"),
        ("Darwin", "darwin", "arm64"),
    ):
        environment = default_environment()
        environment.update(
            platform_system=system, sys_platform=platform, platform_machine=machine
        )
        environments.append(environment)
    queue = [Requirement(raw) for raw in project["dependencies"]]
    seen, packages = set(), {}
    while queue:
        requirement = queue.pop()
        name = canonicalize_name(requirement.name)
        distribution = metadata.distribution(name)
        if requirement.specifier and distribution.version not in requirement.specifier:
            raise ValueError(f"Installed version does not satisfy {requirement}")
        key = name, tuple(sorted(requirement.extras))
        if key in seen:
            continue
        seen.add(key)
        packages[name] = distribution.version
        for raw in distribution.requires or []:
            dependency = Requirement(raw)
            if dependency.marker is None or any(
                dependency.marker.evaluate({**env, "extra": extra})
                for env in environments
                for extra in ("", *requirement.extras)
            ):
                queue.append(dependency)

    def release(item):
        name, version = item
        with urllib.request.urlopen(
            f"https://pypi.org/pypi/{name}/{version}/json",
            timeout=30,
            context=ssl.create_default_context(cafile=certifi.where()),
        ) as response:
            data = json.load(response)
        hashes = sorted(
            {
                file["digests"]["sha256"]
                for file in data["urls"]
                if not file.get("yanked")
            }
        )
        if not hashes or any(len(value) != 64 for value in hashes):
            raise ValueError(f"No acceptable release hashes for {name}")
        return (
            name
            + "=="
            + version
            + " \\\n"
            + " \\\n".join("    --hash=sha256:" + value for value in hashes)
        )

    with ThreadPoolExecutor(max_workers=4) as executor:
        lines = list(executor.map(release, sorted(packages.items())))
    Path("requirements.lock").write_text(
        "# Python 3.12, Linux x86_64/aarch64 and macOS arm64. Verified installed versions.\n# Generated by scripts/lock_verified_dependencies.py; refresh after audit/testing.\n--index-url https://pypi.org/simple\n\n"
        + "\n\n".join(lines)
        + "\n"
    )
    Path("audit/implementation-2026-09-21/runtime-versions.json").write_text(
        json.dumps(packages, indent=2, sort_keys=True)
    )
    print(f"Locked {len(packages)} runtime distributions")


if __name__ == "__main__":
    main()
