"""Logical ER diagram of the administrative records kept as JSON documents.

Each kind in application/compliance.py SCHEMAS is stored as rows of the physical
table compliance_entities (kind, entity_id, person_id, payload) with its history in
compliance_revisions, and is copied into planning inputs. The references between
kinds are string fields inside the payload, not foreign keys; devtools/er/refs.toml
says what each one points to.

    python -m devtools.er.logical [--write | --check]
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path
from typing import Any

from shift_scheduler.application import compliance

HERE = Path(__file__).resolve().parent
OUT = HERE.parents[1] / "docs" / "architecture" / "er"
# Kinds the generic record route refuses (api/routers/compliance.py save()): their own routes
# check balances, self-service rules or actual-work coupling.
DEDICATED = frozenset(
    {
        "leave_record",
        "grant_amendment",
        "leave_amendment",
        "outside_declaration",
        "work_terms",
    }
)
GROUP = {
    **dict.fromkeys(compliance.SCHEMAS, "base"),
    **dict.fromkeys(compliance.V3_SCHEMAS, "v3"),
    **dict.fromkeys(compliance.ADMIN_SCHEMAS, "admin"),
    "outside_declaration": "v3",
}


def refs() -> dict[str, Any]:
    return tomllib.loads((HERE / "refs.toml").read_text())


def entities() -> list[dict[str, Any]]:
    table = refs()
    result = []
    for kind, (model, key, collection) in compliance.SCHEMAS.items():
        # A qualification is identified by the hash of its content (save_entity), not by person_id.
        key = "content_hash" if kind == "capability" else key
        names = [
            n
            for n in model.model_fields
            if n != key and (n.endswith(("_id", "_ids")) or n in table["targets"])
        ]
        names += [n for n in table["extra"].get(kind, []) if n not in names]
        links, identifiers = [], []
        for name in names:
            if name in table["targets"]:
                links.append((name, table["targets"][name]))
            elif name in table["identifiers"]:
                identifiers.append(name)
            else:
                raise ValueError(
                    f"{kind}.{name} is not described in devtools/er/refs.toml"
                )
        result.append(
            {
                "kind": kind,
                "model": model.__name__,
                "key": key,
                "collection": collection,
                "group": GROUP.get(kind, "base"),
                "procedure_only": kind in compliance.PROCEDURE_ONLY,
                "route": (
                    "2人確認の手続だけ"
                    if kind in compliance.PROCEDURE_ONLY
                    else "専用の操作" if kind in DEDICATED else "汎用の記録"
                ),
                "links": links,
                "identifiers": identifiers,
            }
        )
    return result


def mermaid(data: list[dict[str, Any]] | None = None) -> str:
    data = data or entities()
    lines = [
        "%% Generated by devtools/er/logical.py from SCHEMAS and refs.toml. Do not edit.",
        "%% All kinds are rows of compliance_entities (payload JSON); lines are payload references, not FKs.",
        "erDiagram",
        "    accTitle: 論理ER図（管理記録のJSONの参照）",
        f"    accDescr: compliance_entities の payload に入る {len(data)} 種類の記録と、その中の参照を描く。"
        " 線は外部キーではなく JSON の中の参照。一覧は logical.md にもある。",
    ]
    for e in data:
        lines.append(f"    {e['kind']} {{")
        lines.append(f"        string {e['key']} PK \"{e['model']}\"")
        for name, _ in e["links"]:
            lines.append(f'        string {name} FK "payload reference"')
        for name in e["identifiers"]:
            lines.append(f'        string {name} "identifier without a record"')
        lines.append("    }")
    for e in data:
        for name, target in e["links"]:
            for each in target.split("|"):
                label = (
                    each.split(":", 1)[-1].replace(".", "_") if ":" in each else each
                )
                lines.append(f"    {label} ||..o{{ {e['kind']} : \"{name}\"")
    return "\n".join(lines) + "\n"


def dot(data: list[dict[str, Any]] | None = None) -> str:
    data = data or entities()
    colors = {"base": "#e8eef7", "v3": "#e6f4ea", "admin": "#fef7e0"}
    lines = [
        "// Generated by devtools/er/logical.py from SCHEMAS and refs.toml. Do not edit.",
        "digraph logical {",
        '  graph [rankdir=LR, fontname="Noto Sans JP", fontsize=10];',
        '  node [shape=box, style="rounded,filled", fontname="Noto Sans JP", fontsize=9];',
        '  edge [style=dashed, fontname="Noto Sans JP", fontsize=8];',
    ]
    for e in data:
        note = "\\n(2人確認の手続だけで保存)" if e["procedure_only"] else ""
        lines.append(
            f'  "{e["kind"]}" [label="{e["kind"]}\\n{e["model"]}{note}", fillcolor="{colors[e["group"]]}"];'
        )
    for e in data:
        for name, target in e["links"]:
            for each in target.split("|"):
                node = each.split(":", 1)[-1] if ":" in each else each
                if ":" in each:
                    lines.append(
                        f'  "{node}" [shape=cylinder, style=filled, fillcolor="#f1f3f4"];'
                    )
                lines.append(f'  "{e["kind"]}" -> "{node}" [label="{name}"];')
    lines.append("}")
    return "\n".join(lines) + "\n"


def table_md(data: list[dict[str, Any]] | None = None) -> str:
    data = data or entities()
    rows = [
        "<!-- Generated by devtools/er/logical.py. Do not edit. -->",
        "# 論理エンティティ（JSON の記録）",
        "",
        "すべて物理表 `compliance_entities`（種類・識別子・本人・版・payload）に保存し、版の履歴は `compliance_revisions` に残る。"
        "勤務計画の入力（`planning_inputs.payload`）には、各コレクションの写しが入る。参照は payload 内の文字列で、外部キーではない。",
        "",
        "| 種類 | モデル | 識別子 | 入力のコレクション | 参照先 | 記録を持たない識別子 | 保存の経路 |",
        "|---|---|---|---|---|---|---|",
    ]
    for e in data:
        links = "、".join(f"`{n}`→{t}" for n, t in e["links"]) or "—"
        ids = "、".join(f"`{n}`" for n in e["identifiers"]) or "—"
        route = e["route"]
        rows.append(
            f"| `{e['kind']}` | {e['model']} | `{e['key']}` | `{e['collection']}` | {links} | {ids} | {route} |"
        )
    notes = refs()["identifiers"]
    rows += ["", "## 記録を持たない識別子", ""] + [
        f"- `{k}`：{v}" for k, v in notes.items()
    ]
    return "\n".join(rows) + "\n"


def outputs() -> dict[str, str]:
    data = entities()
    return {
        "logical.mmd": mermaid(data),
        "logical.dot": dot(data),
        "logical.md": table_md(data),
    }


def main(argv: list[str]) -> int:
    from devtools.er.physical import svg

    if "--check" in argv:
        stale = [
            n
            for n, t in outputs().items()
            if not (OUT / n).exists() or (OUT / n).read_text() != t
        ]
        print("stale: " + ", ".join(stale) if stale else "logical ER is current")
        return 1 if stale else 0
    if "--write" in argv:
        OUT.mkdir(parents=True, exist_ok=True)
        files = outputs()
        for name, text in files.items():
            (OUT / name).write_text(text)
        (OUT / "logical.svg").write_text(svg(files["logical.dot"]))
        print(f"wrote {len(files) + 1} files to {OUT}")
        return 0
    sys.stdout.write(mermaid())
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
