"""Physical ER diagram from the SQLAlchemy metadata (the tables the migrations create).

Physical foreign keys are drawn as relationships. Many identifiers (person_id,
scope_id, employer_id ...) are plain strings without a foreign key; they are not
drawn here but in the logical diagram (devtools/er/logical.py), so the two kinds of
reference stay apart.

    python -m devtools.er.physical            # print the Mermaid text
    python -m devtools.er.physical --write    # write docs/architecture/er/physical.*
    python -m devtools.er.physical --check    # exit 1 if the stored files are stale
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

from sqlalchemy import CheckConstraint, UniqueConstraint, create_engine, inspect
from sqlalchemy.dialects import postgresql

from shift_scheduler.db import (
    models,  # noqa: F401  (imports the planning and compliance models too)
)
from shift_scheduler.db.base import Base

OUT = Path(__file__).resolve().parents[2] / "docs" / "architecture" / "er"
GROUPS = {
    "legacy": "shift_scheduler.db.models",
    "planning": "shift_scheduler.db.planning_models",
    "compliance": "shift_scheduler.db.compliance_models",
}


def tables() -> list[dict[str, Any]]:
    """Tables with columns, keys and the module (group) that defines them, sorted by name."""
    owner: dict[str, str] = {}
    for mapper in Base.registry.mappers:
        for table in mapper.tables:
            owner[table.name] = next(
                (g for g, m in GROUPS.items() if mapper.class_.__module__ == m), "other"
            )
    result = []
    for table in sorted(Base.metadata.tables.values(), key=lambda t: t.name):
        fks = sorted(
            (fk.parent.name, fk.column.table.name, fk.column.name)
            for fk in table.foreign_keys
        )
        unique = sorted(
            tuple(c.name for c in u.columns)
            for u in table.constraints
            if isinstance(u, UniqueConstraint)
        )
        result.append(
            {
                "name": table.name,
                "group": owner.get(table.name, "other"),
                "columns": [
                    {
                        "name": c.name,
                        "type": _type(c.type),
                        "database_type": str(
                            c.type.compile(dialect=postgresql.dialect())
                        ),
                        "pk": c.primary_key,
                        "nullable": c.nullable,
                        "fk": any(f[0] == c.name for f in fks),
                    }
                    for c in table.columns
                ],
                "foreign_keys": fks,
                "unique": unique,
                "foreign_key_groups": [
                    {
                        "columns": [e.parent.name for e in fk.elements],
                        "target": fk.referred_table.name,
                        "target_columns": [e.column.name for e in fk.elements],
                    }
                    for fk in sorted(
                        table.foreign_key_constraints,
                        key=lambda f: tuple(e.parent.name for e in f.elements),
                    )
                ],
                "checks": sorted(
                    str(c.sqltext)
                    for c in table.constraints
                    if isinstance(c, CheckConstraint)
                ),
                "indexes": sorted(
                    [
                        {
                            "name": i.name,
                            "columns": [c.name for c in i.columns],
                            "unique": i.unique,
                        }
                        for i in table.indexes
                    ],
                    key=lambda i: i["name"],
                ),
            }
        )
    return result


def _type(value: Any) -> str:
    text = str(
        value.__class__.__name__ if value.__class__.__name__ == "JSON" else value
    )
    return re.sub(r"[^A-Za-z0-9]", "_", text).strip("_") or "value"


def mermaid(data: list[dict[str, Any]] | None = None) -> str:
    data = tables() if data is None else data
    lines = [
        "%% Generated by devtools/er/physical.py from the SQLAlchemy metadata. Do not edit.",
        "erDiagram",
        "    accTitle: 物理ER図（データベースの表と外部キー）",
        f"    accDescr: SQLAlchemy のメタデータから生成した {len(data)} 個の表と、宣言された外部キーだけを描く。"
        " JSON の中の参照は論理ER図に描く。表の一覧は physical.dot と physical.svg にもある。",
    ]
    for t in data:
        lines.append(f"    {t['name']} {{")
        for c in t["columns"]:
            keys = ",".join(k for k, on in (("PK", c["pk"]), ("FK", c["fk"])) if on)
            note = "NULL" if c["nullable"] and not c["pk"] else "NOT_NULL"
            lines.append(
                f"        {c['type']} {c['name']}{(' ' + keys) if keys else ''} \"{note}\""
            )
        lines.append("    }")
    for t in data:
        groups = t.get(
            "foreign_key_groups",
            [{"columns": [c], "target": target} for c, target, _ in t["foreign_keys"]],
        )
        for fk in groups:
            columns = set(fk["columns"])
            nullable = any(c["nullable"] for c in t["columns"] if c["name"] in columns)
            primary = {c["name"] for c in t["columns"] if c["pk"]}
            unique_keys = [set(u) for u in t["unique"]] + ([primary] if primary else [])
            unique = any(u and u <= columns for u in unique_keys)
            parent = "|o" if nullable else "||"
            child = "o|" if unique else "o{"
            relationship = "--" if columns <= primary else ".."
            label = ",".join(fk["columns"])
            lines.append(
                f"    {fk['target']} {parent}{relationship}{child} {t['name']} : \"{label}\""
            )
    return "\n".join(lines) + "\n"


def dot(data: list[dict[str, Any]] | None = None) -> str:
    data = data or tables()
    lines = [
        "// Generated by devtools/er/physical.py from the SQLAlchemy metadata. Do not edit.",
        "digraph physical {",
        '  graph [rankdir=LR, fontname="Noto Sans JP", fontsize=10, splines=true];',
        '  node [shape=plaintext, fontname="Noto Sans JP", fontsize=9];',
        '  edge [fontname="Noto Sans JP", fontsize=8];',
    ]
    for group in (*GROUPS, "other", "database"):
        members = [t for t in data if t["group"] == group]
        if not members:
            continue
        lines.append(f'  subgraph cluster_{group} {{ label="{group}"; color="#9aa0a6";')
        for t in members:
            rows = "".join(
                f'<TR><TD ALIGN="LEFT">{"<B>" if c["pk"] else ""}{c["name"]}{"</B>" if c["pk"] else ""}'
                f'{" (FK)" if c["fk"] else ""}</TD><TD ALIGN="LEFT">{c["type"].lower()}</TD></TR>'
                for c in t["columns"]
            )
            lines.append(
                f'    "{t["name"]}" [label=<<TABLE BORDER="1" CELLBORDER="0" CELLSPACING="0" CELLPADDING="3">'
                f'<TR><TD COLSPAN="2" BGCOLOR="#e8eef7"><B>{t["name"]}</B></TD></TR>{rows}</TABLE>>];'
            )
        lines.append("  }")
    for t in data:
        for column, target, target_column in t["foreign_keys"]:
            lines.append(
                f'  "{t["name"]}" -> "{target}" [label="{column}→{target_column}"];'
            )
    lines.append("}")
    return "\n".join(lines) + "\n"


def svg(dot_text: str) -> str:
    """Render with the local Graphviz; the version comment is removed so output is stable."""
    rendered = subprocess.run(
        ["dot", "-Tsvg"], input=dot_text, capture_output=True, text=True, check=True
    ).stdout
    return re.sub(r"<!-- Generated by graphviz[^>]*-->\n", "", rendered)


def outputs() -> dict[str, str]:
    data = tables()
    return {"physical.mmd": mermaid(data), "physical.dot": dot(data)}


def database_tables(connection: Any) -> list[dict[str, Any]]:
    """Actual migrated database inventory. No writes, row contents, or credentials."""
    inspector = inspect(connection)
    result = []
    for name in sorted(inspector.get_table_names()):
        keys = inspector.get_foreign_keys(name)
        pk = set(inspector.get_pk_constraint(name)["constrained_columns"])
        unique = [
            tuple(u["column_names"]) for u in inspector.get_unique_constraints(name)
        ]
        indexes = inspector.get_indexes(name)
        unique.extend(
            tuple(i["column_names"])
            for i in indexes
            if i.get("unique")
            and all(i["column_names"])
            and not i.get("dialect_options", {}).get("postgresql_where")
        )
        fks = sorted(
            (c, f["referred_table"], target)
            for f in keys
            for c, target in zip(
                f["constrained_columns"], f["referred_columns"], strict=True
            )
        )
        result.append(
            {
                "name": name,
                "group": "database",
                "columns": [
                    {
                        "name": c["name"],
                        "type": _type(c["type"]),
                        "database_type": str(
                            c["type"].compile(dialect=connection.dialect)
                        ),
                        "pk": c["name"] in pk,
                        "nullable": c["nullable"],
                        "fk": any(f[0] == c["name"] for f in fks),
                    }
                    for c in inspector.get_columns(name)
                ],
                "foreign_keys": fks,
                "unique": sorted(set(unique)),
                "foreign_key_groups": [
                    {
                        "columns": f["constrained_columns"],
                        "target": f["referred_table"],
                        "target_columns": f["referred_columns"],
                    }
                    for f in keys
                ],
                "checks": inspector.get_check_constraints(name),
                "indexes": indexes,
            }
        )
    return result


def main(argv: list[str]) -> int:
    if "--database-env" in argv:
        parser = argparse.ArgumentParser()
        parser.add_argument("--database-env", required=True)
        parser.add_argument(
            "--label", required=True, choices=["app", "control", "witness"]
        )
        parser.add_argument("--output", required=True, type=Path)
        args = parser.parse_args(argv)
        engine = create_engine(os.environ[args.database_env])
        if engine.dialect.name != "postgresql":
            raise ValueError("Acceptance inventory requires PostgreSQL")
        with engine.connect() as connection:
            connection.exec_driver_sql("SET TRANSACTION READ ONLY")
            data = database_tables(connection)
        engine.dispose()
        args.output.mkdir(parents=True, exist_ok=False)
        (args.output / "schema.json").write_text(
            json.dumps({"label": args.label, "tables": data}, indent=2, default=str)
        )
        text = mermaid(data).replace(
            "from the SQLAlchemy metadata", "from the migrated PostgreSQL database"
        )
        (args.output / "physical.mmd").write_text(text)
        return 0
    if "--check" in argv:
        stale = [
            name
            for name, text in outputs().items()
            if not (OUT / name).exists() or (OUT / name).read_text() != text
        ]
        print("stale: " + ", ".join(stale) if stale else "physical ER is current")
        return 1 if stale else 0
    if "--write" in argv:
        OUT.mkdir(parents=True, exist_ok=True)
        files = outputs()
        for name, text in files.items():
            (OUT / name).write_text(text)
        (OUT / "physical.svg").write_text(svg(files["physical.dot"]))
        print(f"wrote {len(files) + 1} files to {OUT}")
        return 0
    sys.stdout.write(mermaid())
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
