"""Generate the ideal-UI sequence diagrams and text alternatives, one per use case.

The machine-readable contract is the only input. Diagrams intentionally show API and
persistence responsibilities without inventing JSON references as physical foreign keys.

    PYTHONPATH=src:. python -m devtools.er.usecase_sequences [--write | --check]
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "docs" / "ideal-ui" / "usecases.json"
OUT = ROOT / "docs" / "architecture" / "er" / "usecase-sequences.md"


def safe(value: str) -> str:
    return value.replace("<", "&lt;").replace(">", "&gt;").replace("|", "&#124;")


def api_label(value: str) -> str:
    return re.sub(r"\{([^}]+)\}", r":\1", value)


def render() -> str:
    rows = json.loads(SOURCE.read_text(encoding="utf-8"))["use_cases"]
    lines = [
        "<!-- Generated by devtools/er/usecase_sequences.py. Do not edit. -->",
        f"# 理想UI・全{len(rows)}系列のシーケンス",
        "",
        "`docs/ideal-ui/usecases.json` から生成する。API は OpenAPI で別途照合し、保存先は物理ER図と論理参照図で確認する。",
        "図を読めない環境向けに、各図の直後へ同じ順序の表を置く。表名を物理FKとして解釈してはならない。",
        "",
    ]
    for row in rows:
        apis = row["apis"]
        entities = row["entities"]
        lines += [
            f"## {row['id']} {row['title']}",
            "",
            f"経路: `{row['route']}` / 画面: `{row['screen']}/{row['view']}` / 役割: {', '.join(row['roles'])} / E2E: `{row['e2e']}`",
            "",
            "```mermaid",
            "sequenceDiagram",
            f"  accTitle: {row['id']} {row['title']}",
            f"  accDescr: {row['route']} からサーバー認可済みAPIを呼び、記録を読み書きして結果を表示する。",
            "  actor User as 利用者",
            "  participant UI as 理想UI",
            "  participant API as FastAPI",
            "  participant DB as PostgreSQL",
            "  User->>UI: 目的を選ぶ",
        ]
        for api in apis:
            lines += [
                f"  UI->>API: {api_label(api)}",
                f"  API->>DB: {', '.join(entities)} を照合",
                "  DB-->>API: 現在版または競合",
                "  API-->>UI: 役割で制限した結果",
            ]
        lines += [
            "  UI-->>User: 状態と次の操作を表示",
            "```",
            "",
            "| 順序 | 主体 | 操作 | 検証可能な記録 |",
            "|---:|---|---|---|",
            f"| 1 | 利用者 → UI | {safe(row['route'])} で目的を選択 | 画面状態: {safe(', '.join(row['states']))} |",
        ]
        for index, api in enumerate(apis, 2):
            lines.append(
                f"| {index} | UI → API → DB | {safe(api)} | {safe(', '.join(entities))} |"
            )
        lines += [
            f"| {len(apis) + 2} | API → UI | 認可済み結果、または区別された失敗 | 監査: {safe(', '.join(row['audit_events']) or 'なし')} |",
            f"| {len(apis) + 3} | UI → 関連画面 | 列挙済み遷移だけを生成 | {safe(', '.join(row['transitions']))} |",
            "",
        ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    content = render()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else None
        print(
            "use-case sequences are current"
            if current == content
            else "stale: usecase-sequences.md"
        )
        return 0 if current == content else 1
    if "--write" in argv:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(content, encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT)}")
        return 0
    sys.stdout.write(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
