"use client";
import {useEffect,useRef,useState} from 'react';
import ExternalCopyForm from './ExternalCopyForm';
import useUnsavedNavigation,{confirmDiscardChanges} from '@/features/workspace/shared/useUnsavedNavigation';
import SharedPreservationReview from './SharedPreservationReview';
import ConflictTable from '@/features/workspace/shared/ConflictTable';
import {API_BASE_URL as API} from '@/lib/apiTarget';
import {errorText} from '@/lib/errorText';
type Target={copy_id:string;medium:string;revision:number;blockers:string[];expires_at:string|null;preservation?:{payload_hash:string}};
type Preview={plan_id:string;fingerprint:string;revision:number;targets:Target[];unverified_copies:string[];database_records_remaining:string[];database_inventory?:{control_records_remaining:{table:string;object:string;subject_relation:string;purpose:string;retention_status:string;reason:string}[]}};
type Hold={hold_id:string;revision:number;person_id:string|null;active:boolean;payload:{reason?:string}};
const holdLabels:Record<string,string>={hold_id:'保全記録',revision:'版',person_id:'対象職員',active:'保全中','payload.reason':'判断理由','payload.actor':'記録者',reason:'判断理由',expected_revision:'基準の版'};
const reasons:Record<string,string>={subject_inventory_unverified:'対象者一覧が未確認',legal_hold:'法的保全中',shared_copy_schema_unsupported:'この共有形式の再構成は未対応',shared_copy_requires_separate_preservation_decision:'複数職員を含むため保全判断が必要',retention_rule_missing:'保存規則が未登録',retention_rule_unverified_or_stale:'保存規則が未確認または確認期限切れ',retention_not_expired:'保存期限内',external_confirmation_required:'管理先の消去確認が必要',retained_database_references:'保存対象の参照元が残っています',cyclic_database_references:'循環参照の保全判断が必要',database_locator_unsupported:'未対応のDB記録',database_source_missing:'DB正本との照合が必要',database_erasure_requires_postgresql:'DB消去にはPostgreSQLが必要',retention_anchor_mismatch:'保存規則と起算日が一致しません'};
export default function CopyManagement({scope}:{scope:string}){
 const [accountPreview,setAccountPreview]=useState<{preview_hash:string;changes:{copy_id:string;additional_person_ids:string[]}[];unresolved_copy_ids:string[]}|null>(null);
 const [person,setPerson]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [people,setPeople]=useState<{person_id:string;name:string}[]>([]),[holds,setHolds]=useState<Hold[]>([]),[selectedHold,setSelectedHold]=useState('');
 const [dirty,setDirty]=useState(false);useUnsavedNavigation(dirty);
 const [holdConflict,setHoldConflict]=useState<{base:Hold|undefined;current:Hold;proposed:unknown;holds:Hold[]}|null>(null);
 const retry=useRef<{serialized:string;key:string}|null>(null);
 async function read(path:string){const response=await fetch(`${API}/planning/compliance${path}${path.includes('?')?'&':'?'}scope_id=${encodeURIComponent(scope)}`,{credentials:'include',cache:'no-store'});if(!response.ok)throw new Error('現在の対象と権限を確認できません。再読込してください。');return response.json();}
 async function refresh(){const privacy=await read('/privacy');setPeople(privacy.people);setHolds(privacy.holds);}
 useEffect(()=>{let active=true;void read('/privacy').then(p=>{if(active){setPeople(p.people);setHolds(p.holds);}}).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};},[scope]); // eslint-disable-line react-hooks/exhaustive-deps
 async function call(path:string,payload:unknown,revision=0){const serialized=JSON.stringify({path,payload,revision});if(retry.current?.serialized!==serialized)retry.current={serialized,key:crypto.randomUUID()};const response=await fetch(`${API}/planning/compliance${path}?scope_id=${encodeURIComponent(scope)}`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({payload,expected_revision:revision,idempotency_key:retry.current.key})});if(response.status===409&&path==='/holds'){const next=await read('/privacy');const body=payload as {hold_id?:string};const current=next.holds.find((h:Hold)=>h.hold_id===body.hold_id);if(current)setHoldConflict({base:holds.find(h=>h.hold_id===body.hold_id),current,proposed:payload,holds:next.holds});}if(!response.ok)throw new Error(response.status===409?'対象・版・保全状態が変わりました。再確認してください。':'操作を保存できませんでした。入力と権限を確認してください。');return response.json();}
 async function act(operation:()=>Promise<void>){setBusy(true);setError('');try{await operation();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 const hold=holds.find(h=>h.hold_id===selectedHold);
 return <details><summary>コピーの残存・消去予約と法的保全</summary><p>バックアップ、外部コピー、未確認記録の残存を区別します。共有記録は、他の職員の保全内容を確認してから旧版を消去します。管理ファイルはworkerが保全状態を再確認します。</p>
 <ExternalCopyForm people={people} save={call} onChanged={()=>{setPreview(null);}}/>
 <section className="workflow-panel border p-3 my-3 space-y-2" aria-label="操作者参照の照合"><h3 className="font-semibold">既存記録の操作者参照を照合</h3><p>氏名や自由記述から推測せず、アカウント対応から人物参照の追加候補を抽出します。原本・内容ハッシュ・保存起算日は変更しません。</p><button className="ui-button ui-button-secondary" disabled={busy} onClick={()=>void act(async()=>setAccountPreview(await read('/copies/account-backfill')))}>操作者参照の追加候補を確認</button>
 {accountPreview&&<><p>追加候補 {accountPreview.changes.length}件、人物対応が未確定 {accountPreview.unresolved_copy_ids.length}件。適用後は対象者一覧を再確認してください。</p><button className="ui-button ui-button-secondary" disabled={busy||!accountPreview.changes.length} onClick={()=>void act(async()=>{const result=await call('/copies/account-backfill',{preview_hash:accountPreview.preview_hash});setAccountPreview(null);setPreview(null);setMessage(`${result.updated_copies}件の参照を追加しました。以前の対象者確認は無効になりました。`);})}>この確認版の参照を追加</button></>}
 </section>
 <label className="block">対象職員<select aria-label="対象職員" value={person} onChange={e=>{if(!confirmDiscardChanges('未保存の申告・保全判断を破棄しますか？'))return;setDirty(false);setHoldConflict(null);setPerson(e.target.value);setPreview(null);}} className="ui-control block w-full"><option value="">選択してください（保全の新規登録のみ部署全体を選択可能）</option>{people.map(p=><option key={p.person_id} value={p.person_id}>{p.name}（{p.person_id}）</option>)}</select></label>
 <button className="ui-button ui-button-secondary" disabled={busy||!person} onClick={()=>void act(async()=>{setPreview(await call('/copies/preview',{person_id:person}));setMessage('対象と残存理由を確認してください。');})}>コピーの消去対象を確認</button>
 {preview&&<div><p>登録コピー {preview.targets.length} 件、対象者未確認 {preview.unverified_copies.length} 件、DBの本人記録残存 {preview.database_records_remaining.length} 件</p>
 <details><summary>消去・保全・復元の制御記録の残存（{preview.database_inventory?.control_records_remaining?.length??0}件）</summary><p>再作成防止などに必要な制御記録も保存・利用制限の判断対象です。消去済みには算入しません。</p><ul>{preview.database_inventory?.control_records_remaining?.map(r=><li key={r.object} className="border rounded-control break-words p-3">{r.table}：{r.purpose}／{r.retention_status==='RULE_MISSING'?'保存規則未登録':'保存規則の適用確認が必要'}／{r.subject_relation==='shared_or_unresolved_control'?'共有・人物帰属未確定':'人物・計画参照あり'}。{r.reason}</li>)}</ul></details>
 <ul>{preview.targets.map(t=><li key={t.copy_id} className="break-words border rounded-control p-3">{t.copy_id}：{t.medium==='backup'?'バックアップ':t.medium==='external'?'外部コピー':t.medium==='database'?'DB記録':'管理ファイル'}／{t.blockers.length?t.blockers.map(b=>reasons[b]??b).join('、'):'消去実行可能'}{t.expires_at&&`／保存期限 ${t.expires_at}`}{t.medium==='external'&&<form className="border rounded-control space-y-2 p-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(async()=>{await call('/copies/confirm-external',{copy_id:t.copy_id,evidence:{reference:String(f.get('reference')),status:'verified',verified_by:String(f.get('reviewer'))}},t.revision);setPreview(null);setMessage('外部管理先の処理確認を記録しました。端末や媒体の物理消去をアプリが検証した意味ではありません。残存を再照合してください。');});}}><p>外部管理先から取得した消去・処理の確認を記録します。保存期限・保全・原本ハッシュ・現在版を API が再検査します。</p><label className="block">外部管理先の処理確認資料<input name="reference" required className="ui-control block w-full"/></label><label className="block">外部処理の確認担当者<input name="reviewer" required className="ui-control block w-full"/></label><button className="ui-button ui-button-secondary" disabled={busy}>外部管理先の確認を記録</button></form>}{t.preservation&&<SharedPreservationReview copyId={t.copy_id} personId={person} read={read} save={call} onChanged={()=>{setPreview(null);setMessage('保全判断を記録しました。消去対象を再確認してください。');}}/>}</li>)}</ul>
 <button className="ui-button ui-button-danger border-danger" disabled={busy||!preview.targets.some(t=>t.blockers.length===0)} onClick={()=>void act(async()=>{const result=await call('/copies/execute',{plan_id:preview.plan_id,fingerprint:preview.fingerprint},preview.revision);setPreview(null);setMessage(`DB記録 ${result.erased_database_copy_ids?.length??0} 件を消去、部分履歴 ${result.preserved_archive_ids?.length??0} 件を保全、ファイル ${result.queued_copy_ids.length} 件を予約しました。全コピーの消去完了ではありません。残存を再確認してください。`);})}>この確認版の消去可能分を実行</button></div>}
 <form key={person+':'+selectedHold} className="space-y-2 mt-4" onChange={e=>{if((e.target as HTMLElement).getAttribute('name'))setDirty(true);}} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(async()=>{const saved=await call('/holds',{hold_id:hold?.hold_id,person_id:hold?hold.person_id:person||null,active:f.get('active')==='hold',reason:f.get('reason')},hold?.revision??0);setDirty(false);setHoldConflict(null);setPreview(null);await refresh();setSelectedHold(saved.hold_id);setMessage(`保全判断を記録しました（版 ${saved.revision}）。`);});}}>
 <p>新規登録で対象職員が未選択の場合、部署全体を保全します。既存保全の対象と現在版は登録記録から取得します。</p>
 <label className="block">対象の保全記録<select aria-label="対象の保全記録" value={selectedHold} onChange={e=>{if(!confirmDiscardChanges('未保存の申告・保全判断を破棄しますか？'))return;setDirty(false);setHoldConflict(null);setSelectedHold(e.target.value);}} className="ui-control block w-full"><option value="">新規に保全する</option>{holds.map(h=><option key={h.hold_id} value={h.hold_id}>{h.person_id??'部署全体'}：{h.active?'保全中':'解除済み'}（版 {h.revision}）</option>)}</select></label>
 <label className="block">保全操作<select name="active" className="ui-control block"><option value="hold">保全する</option><option value="release" disabled={!hold}>保全を解除する</option></select></label>
 <label className="block">判断理由<textarea name="reason" defaultValue={hold?.payload.reason??''} required className="ui-control block w-full"/></label><button className="ui-button ui-button-secondary" disabled={busy||!!holdConflict}>保全判断を記録</button></form>
 {holdConflict&&<section aria-label="保全判断の更新競合" className="workflow-panel border p-3 break-words"><h3>保全判断の更新競合</h3><p role="alert">別の更新があります。三つの保全判断を比べて確認してください。</p><ConflictTable base={holdConflict.base} current={holdConflict.current} proposed={holdConflict.proposed} labels={holdLabels}/><button className="ui-button ui-button-secondary" onClick={()=>{setHolds(holdConflict.holds);setHoldConflict(null);retry.current=null;setMessage('三つの保全判断を確認しました。保持した内容で改めて保存してください。');}}>三つの保全判断を確認して再送を許可</button></section>}
 <button className="ui-button ui-button-secondary" disabled={busy} onClick={()=>{if(!confirmDiscardChanges('未保存の保全判断を破棄して再読込しますか？'))return;setDirty(false);setHoldConflict(null);void act(refresh);}}>対象と保全状態を再読込</button>
 {error&&<p role="alert">{error}</p>}<p role="status">{busy?'処理中…':message}</p></details>;
}
