"use client";
import {useRef,useState} from 'react';
import useUnsavedNavigation from '@/features/workspace/shared/useUnsavedNavigation';
type Person={person_id:string;name:string};
export default function ExternalCopyForm({people,save,onChanged}:{people:Person[];save:(path:string,payload:unknown,revision?:number)=>Promise<unknown>;onChanged:()=>void}){
 const [dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[hash,setHash]=useState(''),[fileName,setFileName]=useState(''),[selected,setSelected]=useState<string[]>([]);
 const hashingGeneration=useRef(0);
 const id=useRef<string>('');useUnsavedNavigation(dirty);
 return <details><summary>外部へ渡した出力物を登録</summary><p>対象ファイルはこの端末でハッシュを計算し、本文を送信しません。管理ファイル・バックアップは作成経路が自動登録します。外部の印刷物・複製先も処理確認までは残存です。</p>
 <form className="space-y-2" onChange={()=>setDirty(true)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');if(!id.current)id.current=crypto.randomUUID();void(async()=>{try{if(!hash||!selected.length)throw new Error('原本ファイルと対象職員を選んでください。');await save('/copies/register',{copy_id:id.current,category:'exports',medium:'external',relative_path:String(f.get('destination')),content_hash:hash,person_ids:selected,anchor:String(f.get('anchor')),anchor_at:new Date(String(f.get('at'))+'+09:00').toISOString(),subject_status:f.get('verified')?'VERIFIED':'UNVERIFIED',evidence:{reference:String(f.get('reference')),status:f.get('verified')?'verified':'unverified',verified_by:f.get('verified')?String(f.get('reviewer')):null}});setDirty(false);id.current='';setMessage('外部コピーの来歴を登録しました。外部の実消去を確認した状態ではありません。');onChanged();}catch(ex){setError(String(ex));}finally{setBusy(false);}})();}}>
 <label className="block">受け渡した原本ファイル<input className="ui-control block w-full" type="file" required disabled={busy} onChange={e=>{const generation=++hashingGeneration.current;const file=e.target.files?.[0];setHash('');setFileName(file?.name??'');if(!file)return;void file.arrayBuffer().then(bytes=>crypto.subtle.digest('SHA-256',bytes)).then(bytes=>{if(generation===hashingGeneration.current)setHash(Array.from(new Uint8Array(bytes),x=>x.toString(16).padStart(2,'0')).join(''));}).catch(ex=>{if(generation===hashingGeneration.current)setError(String(ex));});}}/></label><p className="break-all">{fileName?`${fileName}：${hash||'ハッシュ計算中'}`:'原本未選択'}</p>
 <fieldset className="workflow-fieldset"><legend>ファイルに含む対象職員</legend>{people.map(p=><label className="block" key={p.person_id}><input className="ui-choice" type="checkbox" checked={selected.includes(p.person_id)} onChange={e=>setSelected(old=>e.target.checked?[...old,p.person_id]:old.filter(id=>id!==p.person_id))}/>{p.name}</label>)}</fieldset>
 <label className="block">受渡し先・管理場所<input name="destination" required className="ui-control block w-full"/></label><label className="block">保存期間の起算方式<select name="anchor" defaultValue="last_activity" className="ui-control block w-full"><option value="period_end">対象期間の終了</option><option value="last_activity">最終更新・受渡し</option><option value="case_closed">本人対応の終了</option><option value="backup_created">バックアップ作成</option></select></label><label className="block">選んだ保存起算の日時（日本時間）<input name="at" required type="datetime-local" step="1" className="ui-control block max-w-full"/></label><label className="block">人物一覧と受渡しの確認根拠<input name="reference" required className="ui-control block w-full"/></label><label className="block">確認者<input name="reviewer" className="ui-control block w-full"/></label><label className="block"><input className="ui-choice" name="verified" type="checkbox"/>原本と全対象者・受渡し先を照合した</label><button className="ui-button ui-button-secondary" disabled={busy||!hash}>外部コピーを登録・再送</button>
 </form>{dirty&&<p role="status">未保存の外部コピー登録があります。</p>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</details>;
}
